LOCAL_PLAIN_TEXT_FILE = 1
LOCAL_JSON_FILE = 2
LOCAL_SQLLITE3 = 3

S3_PLAIN_TEXT_FILE = 4
S3_JSON_FILE = 5
REMOTE_COUCH_DB = 6

MODEL_API_STATUS_UP = 'MODEL_API_STATUS_UP'
MODEL_API_STATUS_DOWN = 'MODEL_API_STATUS_DOWN'
