sudo: false
language: python

python:
    - 2.7
    - pypy
    - 3.4
    - 3.5

env:
    - BUILD=tests
    - BUILD=style

addons:
    apt:
        packages:
            - language-pack-de

install: 
        - "pip install tox"

script:
    - ./.travis.run.sh

matrix:
    exclude:
        - python: pypy
          env: BUILD=style
