
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bc8cae5ef8596212836d55521839d9d2558ded50",
 "version": "0.7.post6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
