
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b739d451a0bb41dbe0a2d133cd340963f283b9bb",
 "version": "0.1.8.post.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
