# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathJaxConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_mathjax_mathjaxconfig', serialize=False, to='cms.CMSPlugin')),
                ('config_file', models.CharField(blank=True, choices=[('TeX-AMS-MML_HTMLorMML', 'TeX-AMS-MML_HTMLorMML'), ('TeX-AMS_HTML', 'TeX-AMS_HTML'), ('MML_HTMLorMML', 'MML_HTMLorMML'), ('AM_HTMLorMML', 'AM_HTMLorMML'), ('TeX-AMS-MML_SVG', 'TeX-AMS-MML_SVG'), ('TeX-MML-AM_HTMLorMML', 'TeX-MML-AM_HTMLorMML')], max_length=100, verbose_name='Configuration preset')),
                ('config_data', models.TextField(blank=True, default='', help_text='javascript code without javascirpt tags. See MathJax docs for details.', verbose_name='Configuration data')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
