# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_mathjax', '0002_auto_20161021_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathjaxconfig',
            name='config_file',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('TeX-MML-AM_CHTML', 'TeX-MML-AM_CHTML'), ('TeX-MML-AM_HTMLorMML', 'TeX-MML-AM_HTMLorMML'), ('TeX-MML-AM_SVG', 'TeX-MML-AM_SVG'), ('TeX-AMS-MML_HTMLorMML', 'TeX-AMS-MML_HTMLorMML'), ('TeX-AMS_CHTML', 'TeX-AMS_CHTML'), ('TeX-AMS_SVG', 'TeX-AMS_SVG'), ('TeX-AMS_HTML', 'TeX-AMS_HTML'), ('MML_CHTML', 'MML_CHTML'), ('MML_SVG', 'MML_SVG'), ('MML_HTMLorMML', 'MML_HTMLorMML'), ('AM_CHTML', 'AM_CHTML'), ('AM_SVG', 'AM_SVG'), ('AM_HTMLorMML', 'AM_HTMLorMML'), ('TeX-AMS-MML_SVG', 'TeX-AMS-MML_SVG')], default='TeX-MML-AM_CHTML', help_text='see <a href="http://docs.mathjax.org/en/latest/config-files.html#common-configurations" target="_blank">Mathjax Doc</a>', max_length=25, verbose_name='Configuration File'),
        ),
        migrations.AlterField(
            model_name='mathjaxconfig',
            name='inline_config',
            field=models.TextField(blank=True, default='', help_text='javascript code, see <a href="http://docs.mathjax.org/en/latest/configuration.html#loading" target="_blank">Mathjax Doc</a>', verbose_name='Inline Configuration'),
        ),
    ]
