
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "fd8bb5ff7657734a109f76578a31d4c8ed7e090d",
 "version": "0.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
