language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
install:
    - pip install coverage coveralls -e .
script:
    - coverage run --source=imgdiff.py tests.py
after_success:
    - coveralls
notifications:
    email: false
