
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "81a86f5c97f6f844ea3d07944a094e09a826271d",
 "version": "1.0.0.post.dev296"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
