from telethon.tl.mtproto_request import MTProtoRequest


class ChannelParticipantsAdmins(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    channelParticipantsAdmins#b4608969  = ChannelParticipantsFilter"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xb4608969

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'channelParticipantsAdmins#b4608969  = ChannelParticipantsFilter'

    def __str__(self):
        return '(channelParticipantsAdmins (ID: 0xb4608969) = ())'.format()
