from telethon.tl.mtproto_request import MTProtoRequest


class ChannelRoleModerator(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    channelRoleModerator#9618d975  = ChannelParticipantRole"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x9618d975

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'channelRoleModerator#9618d975  = ChannelParticipantRole'

    def __str__(self):
        return '(channelRoleModerator (ID: 0x9618d975) = ())'.format()
