from telethon.tl.mtproto_request import MTProtoRequest


class ChatEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    chatEmpty#9ba2d800 id:int = Chat"""

    def __init__(self, id):
        """
        :param id: Telegram type: «int».
        """
        super().__init__()
        self.constructor_id = 0x9ba2d800

        self.id = id

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.write_int(self.id)

    def on_response(self, reader):
        self.id = reader.read_int()

    def __repr__(self):
        return 'chatEmpty#9ba2d800 id:int = Chat'

    def __str__(self):
        return '(chatEmpty (ID: 0x9ba2d800) = (id={}))'.format(str(self.id))
