from telethon.tl.mtproto_request import MTProtoRequest


class ContactLinkHasPhone(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    contactLinkHasPhone#268f3f59  = ContactLink"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x268f3f59

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'contactLinkHasPhone#268f3f59  = ContactLink'

    def __str__(self):
        return '(contactLinkHasPhone (ID: 0x268f3f59) = ())'.format()
