from telethon.tl.mtproto_request import MTProtoRequest


class ContactLinkUnknown(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    contactLinkUnknown#5f4f9247  = ContactLink"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x5f4f9247

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'contactLinkUnknown#5f4f9247  = ContactLink'

    def __str__(self):
        return '(contactLinkUnknown (ID: 0x5f4f9247) = ())'.format()
