from telethon.tl.mtproto_request import MTProtoRequest


class DocumentAttributeSticker(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    documentAttributeSticker#3a556302 alt:string stickerset:InputStickerSet = DocumentAttribute"""

    def __init__(self, alt, stickerset):
        """
        :param alt: Telegram type: «string».
        :param stickerset: Telegram type: «InputStickerSet».
        """
        super().__init__()
        self.constructor_id = 0x3a556302

        self.alt = alt
        self.stickerset = stickerset

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_string(self.alt)
        self.stickerset.on_send(writer)

    def on_response(self, reader):
        self.alt = reader.tgread_string()
        self.stickerset = reader.tgread_object()

    def __repr__(self):
        return 'documentAttributeSticker#3a556302 alt:string stickerset:InputStickerSet = DocumentAttribute'

    def __str__(self):
        return '(documentAttributeSticker (ID: 0x3a556302) = (alt={}, stickerset={}))'.format(str(self.alt), str(self.stickerset))
