from telethon.tl.mtproto_request import MTProtoRequest


class EncryptedFileEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    encryptedFileEmpty#c21f497e  = EncryptedFile"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xc21f497e

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'encryptedFileEmpty#c21f497e  = EncryptedFile'

    def __str__(self):
        return '(encryptedFileEmpty (ID: 0xc21f497e) = ())'.format()
