from telethon.tl.mtproto_request import MTProtoRequest


class InputUserSelf(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputUserSelf#f7c1b13f  = InputUser"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xf7c1b13f

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputUserSelf#f7c1b13f  = InputUser'

    def __str__(self):
        return '(inputUserSelf (ID: 0xf7c1b13f) = ())'.format()
