from telethon.tl.mtproto_request import MTProtoRequest


class InputMessagesFilterPhotos(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputMessagesFilterPhotos#9609a51c  = MessagesFilter"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x9609a51c

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputMessagesFilterPhotos#9609a51c  = MessagesFilter'

    def __str__(self):
        return '(inputMessagesFilterPhotos (ID: 0x9609a51c) = ())'.format()
