from telethon.tl.mtproto_request import MTProtoRequest


class InputMessagesFilterChatPhotos(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputMessagesFilterChatPhotos#3a20ecb8  = MessagesFilter"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x3a20ecb8

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputMessagesFilterChatPhotos#3a20ecb8  = MessagesFilter'

    def __str__(self):
        return '(inputMessagesFilterChatPhotos (ID: 0x3a20ecb8) = ())'.format()
