from telethon.tl.mtproto_request import MTProtoRequest


class InputReportReasonViolence(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputReportReasonViolence#1e22c78d  = ReportReason"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x1e22c78d

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputReportReasonViolence#1e22c78d  = ReportReason'

    def __str__(self):
        return '(inputReportReasonViolence (ID: 0x1e22c78d) = ())'.format()
