from telethon.tl.mtproto_request import MTProtoRequest


class InputPrivacyValueDisallowAll(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputPrivacyValueDisallowAll#d66b66c9  = InputPrivacyRule"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xd66b66c9

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputPrivacyValueDisallowAll#d66b66c9  = InputPrivacyRule'

    def __str__(self):
        return '(inputPrivacyValueDisallowAll (ID: 0xd66b66c9) = ())'.format()
