from telethon.tl.mtproto_request import MTProtoRequest


class InputMessagesFilterGif(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputMessagesFilterGif#ffc86587  = MessagesFilter"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xffc86587

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputMessagesFilterGif#ffc86587  = MessagesFilter'

    def __str__(self):
        return '(inputMessagesFilterGif (ID: 0xffc86587) = ())'.format()
