from telethon.tl.mtproto_request import MTProtoRequest


class InputPrivacyKeyChatInvite(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputPrivacyKeyChatInvite#bdfb0426  = InputPrivacyKey"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xbdfb0426

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputPrivacyKeyChatInvite#bdfb0426  = InputPrivacyKey'

    def __str__(self):
        return '(inputPrivacyKeyChatInvite (ID: 0xbdfb0426) = ())'.format()
