from telethon.tl.mtproto_request import MTProtoRequest


class InputPeerEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputPeerEmpty#7f3b18ea  = InputPeer"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x7f3b18ea

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputPeerEmpty#7f3b18ea  = InputPeer'

    def __str__(self):
        return '(inputPeerEmpty (ID: 0x7f3b18ea) = ())'.format()
