from telethon.tl.mtproto_request import MTProtoRequest


class InputPrivacyValueAllowContacts(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputPrivacyValueAllowContacts#0d09e07b  = InputPrivacyRule"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xd09e07b

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputPrivacyValueAllowContacts#0d09e07b  = InputPrivacyRule'

    def __str__(self):
        return '(inputPrivacyValueAllowContacts (ID: 0xd09e07b) = ())'.format()
