from telethon.tl.mtproto_request import MTProtoRequest


class InputReportReasonSpam(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputReportReasonSpam#58dbcab8  = ReportReason"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x58dbcab8

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputReportReasonSpam#58dbcab8  = ReportReason'

    def __str__(self):
        return '(inputReportReasonSpam (ID: 0x58dbcab8) = ())'.format()
