from telethon.tl.mtproto_request import MTProtoRequest


class InputChatPhoto(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputChatPhoto#b2e1bf08 id:InputPhoto crop:InputPhotoCrop = InputChatPhoto"""

    def __init__(self, id, crop):
        """
        :param id: Telegram type: «InputPhoto».
        :param crop: Telegram type: «InputPhotoCrop».
        """
        super().__init__()
        self.constructor_id = 0xb2e1bf08

        self.id = id
        self.crop = crop

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        self.id.on_send(writer)
        self.crop.on_send(writer)

    def on_response(self, reader):
        self.id = reader.tgread_object()
        self.crop = reader.tgread_object()

    def __repr__(self):
        return 'inputChatPhoto#b2e1bf08 id:InputPhoto crop:InputPhotoCrop = InputChatPhoto'

    def __str__(self):
        return '(inputChatPhoto (ID: 0xb2e1bf08) = (id={}, crop={}))'.format(str(self.id), str(self.crop))
