from telethon.tl.mtproto_request import MTProtoRequest


class InputNotifyChats(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputNotifyChats#4a95e84e  = InputNotifyPeer"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x4a95e84e

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputNotifyChats#4a95e84e  = InputNotifyPeer'

    def __str__(self):
        return '(inputNotifyChats (ID: 0x4a95e84e) = ())'.format()
