from telethon.tl.mtproto_request import MTProtoRequest


class KeyboardButton(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    keyboardButton#a2fa4880 text:string = KeyboardButton"""

    def __init__(self, text):
        """
        :param text: Telegram type: «string».
        """
        super().__init__()
        self.constructor_id = 0xa2fa4880

        self.text = text

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_string(self.text)

    def on_response(self, reader):
        self.text = reader.tgread_string()

    def __repr__(self):
        return 'keyboardButton#a2fa4880 text:string = KeyboardButton'

    def __str__(self):
        return '(keyboardButton (ID: 0xa2fa4880) = (text={}))'.format(str(self.text))
