from telethon.tl.mtproto_request import MTProtoRequest


class MessageActionHistoryClear(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messageActionHistoryClear#9fbab604  = MessageAction"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x9fbab604

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'messageActionHistoryClear#9fbab604  = MessageAction'

    def __str__(self):
        return '(messageActionHistoryClear (ID: 0x9fbab604) = ())'.format()
