from telethon.tl.mtproto_request import MTProtoRequest


class MessageEntityMentionName(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messageEntityMentionName#352dca58 offset:int length:int user_id:int = MessageEntity"""

    def __init__(self, offset, length, user_id):
        """
        :param offset: Telegram type: «int».
        :param length: Telegram type: «int».
        :param user_id: Telegram type: «int».
        """
        super().__init__()
        self.constructor_id = 0x352dca58

        self.offset = offset
        self.length = length
        self.user_id = user_id

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.write_int(self.offset)
        writer.write_int(self.length)
        writer.write_int(self.user_id)

    def on_response(self, reader):
        self.offset = reader.read_int()
        self.length = reader.read_int()
        self.user_id = reader.read_int()

    def __repr__(self):
        return 'messageEntityMentionName#352dca58 offset:int length:int user_id:int = MessageEntity'

    def __str__(self):
        return '(messageEntityMentionName (ID: 0x352dca58) = (offset={}, length={}, user_id={}))'.format(str(self.offset), str(self.length), str(self.user_id))
