from telethon.tl.mtproto_request import MTProtoRequest


class PhotoSizeEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    photoSizeEmpty#0e17e23c type:string = PhotoSize"""

    def __init__(self, type):
        """
        :param type: Telegram type: «string».
        """
        super().__init__()
        self.constructor_id = 0xe17e23c

        self.type = type

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_string(self.type)

    def on_response(self, reader):
        self.type = reader.tgread_string()

    def __repr__(self):
        return 'photoSizeEmpty#0e17e23c type:string = PhotoSize'

    def __str__(self):
        return '(photoSizeEmpty (ID: 0xe17e23c) = (type={}))'.format(str(self.type))
