from telethon.tl.mtproto_request import MTProtoRequest


class PrivacyValueAllowAll(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    privacyValueAllowAll#65427b82  = PrivacyRule"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x65427b82

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'privacyValueAllowAll#65427b82  = PrivacyRule'

    def __str__(self):
        return '(privacyValueAllowAll (ID: 0x65427b82) = ())'.format()
