from telethon.tl.mtproto_request import MTProtoRequest


class RpcAnswerDroppedRunning(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    rpc_answer_dropped_running#cd78e586  = RpcDropAnswer"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xcd78e586

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'rpc_answer_dropped_running#cd78e586  = RpcDropAnswer'

    def __str__(self):
        return '(rpc_answer_dropped_running (ID: 0xcd78e586) = ())'.format()
