from telethon.tl.mtproto_request import MTProtoRequest


class SendMessageCancelAction(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    sendMessageCancelAction#fd5ec8f5  = SendMessageAction"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xfd5ec8f5

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'sendMessageCancelAction#fd5ec8f5  = SendMessageAction'

    def __str__(self):
        return '(sendMessageCancelAction (ID: 0xfd5ec8f5) = ())'.format()
