from telethon.tl.mtproto_request import MTProtoRequest


class UpdateRecentStickers(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    updateRecentStickers#9a422c20  = Update"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x9a422c20

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'updateRecentStickers#9a422c20  = Update'

    def __str__(self):
        return '(updateRecentStickers (ID: 0x9a422c20) = ())'.format()
