from telethon.tl.mtproto_request import MTProtoRequest


class UpdateUserStatus(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    updateUserStatus#1bfbd823 user_id:int status:UserStatus = Update"""

    def __init__(self, user_id, status):
        """
        :param user_id: Telegram type: «int».
        :param status: Telegram type: «UserStatus».
        """
        super().__init__()
        self.constructor_id = 0x1bfbd823

        self.user_id = user_id
        self.status = status

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.write_int(self.user_id)
        self.status.on_send(writer)

    def on_response(self, reader):
        self.user_id = reader.read_int()
        self.status = reader.tgread_object()

    def __repr__(self):
        return 'updateUserStatus#1bfbd823 user_id:int status:UserStatus = Update'

    def __str__(self):
        return '(updateUserStatus (ID: 0x1bfbd823) = (user_id={}, status={}))'.format(str(self.user_id), str(self.status))
