from telethon.tl.mtproto_request import MTProtoRequest


class UpdateConfig(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    updateConfig#a229dd06  = Update"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xa229dd06

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'updateConfig#a229dd06  = Update'

    def __str__(self):
        return '(updateConfig (ID: 0xa229dd06) = ())'.format()
