from telethon.tl.mtproto_request import MTProtoRequest


class UpdateReadFeaturedStickers(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    updateReadFeaturedStickers#571d2742  = Update"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x571d2742

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'updateReadFeaturedStickers#571d2742  = Update'

    def __str__(self):
        return '(updateReadFeaturedStickers (ID: 0x571d2742) = ())'.format()
