from telethon.tl.mtproto_request import MTProtoRequest


class UpdateSavedGifs(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    updateSavedGifs#9375341e  = Update"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x9375341e

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'updateSavedGifs#9375341e  = Update'

    def __str__(self):
        return '(updateSavedGifs (ID: 0x9375341e) = ())'.format()
