from telethon.tl.mtproto_request import MTProtoRequest


class UserStatusLastMonth(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    userStatusLastMonth#77ebc742  = UserStatus"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x77ebc742

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'userStatusLastMonth#77ebc742  = UserStatus'

    def __str__(self):
        return '(userStatusLastMonth (ID: 0x77ebc742) = ())'.format()
