from telethon.tl.mtproto_request import MTProtoRequest


class UserStatusEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    userStatusEmpty#09d05049  = UserStatus"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x9d05049

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'userStatusEmpty#09d05049  = UserStatus'

    def __str__(self):
        return '(userStatusEmpty (ID: 0x9d05049) = ())'.format()
