heat_template_version: 2016-04-08

description: >
  MySQL with Pacemaker service deployment using puppet

parameters:
  #Parameters not used EndpointMap
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  MysqlBase:
    type: ../../database/mysql.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Service MySQL with Pacemaker using composable services.
    value:
      service_name: mysql
      config_settings:
        get_attr: [MysqlBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::pacemaker::database::mysql
