# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.3
      env: TOX_ENV=py33
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35
    - python: nightly
      env: TOX_ENV=py36


install:
  - pip install -r requirements.txt

script: tox -e $TOX_ENV
