
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "77c83a64b4bb67843249cd5db646f9725f0a6562",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
