
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "37ff85c96756d4680852d47327126ee0f2b3fc14",
 "version": "0.7.post10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
