
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "122e75f8cd8dbebcae9688a1388bcc2578d43084",
 "version": "0.post.dev23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
