
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "72a005f365d11ffb3e18302178bd3cd1b9459d97",
 "version": "0.post.dev27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
