
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7a7d1124adde2b5701e6dd6ab554e7bf1c196ba8",
 "version": "1.2.65"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
