sudo: false
language: python

python:
  - "2.7"

install:
  - pip install tox
  - pip install coveralls
  # some tests work on the git history so we need all of it!
  - git fetch --unshallow

script:
  - tox

after_success:
  - coveralls
