language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - "DJANGO_VERSION=1.9"
  - "DJANGO_VERSION=1.10"
install:
  - "pip install -U pip"
  - "pip install . -c constraints.txt"
  - "pip install -r dev-requirements.txt"
  - "pip install django==$DJANGO_VERSION"
script: python test
