
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.2'
version_full = '8d2d967b0e2602d930f52820b6319c6307190b85'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

