
# This file is automatically generated by setup.py, So don't edit it. :)
VERSION_INFO = {
    'final': True,
    'version': '1.8.4',
    'branch_nick': '(no',
    'revision_id': '85fffdfb3c83bbfd4e45d01100cba956d083f439',
    'revno': 4496
}
