
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bdaef4d876c54cf98901187801dc2fa81871b91e",
 "version": "0.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
