name: smap_io-docs
channels:
- conda-forge
dependencies:
- h5py=2.6.0
- python=2.7
- pyresample
- scipy
- pandas
- netcdf4=1.2.2
- matplotlib
- pip:
  - pygeobase==0.3.9
  - pytesmo
  - pygeogrids
  - repurpose
  - ease_grid
