language: python

cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION="==1.8"
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION="==1.9"
  - DJANGO_VERSION=">=1.9,<1.10"
  - DJANGO_VERSION="==1.10"
  - DJANGO_VERSION=">=1.10,<1.11"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION="==1.9"
    - python: "3.3"
      env: DJANGO_VERSION=">=1.9,<1.10"
    - python: "3.3"
      env: DJANGO_VERSION="==1.10"
    - python: "3.3"
      env: DJANGO_VERSION=">=1.10,<1.11"

install:
  - pip install -q Django$DJANGO_VERSION
  - pip install .

script:
  - make test
