
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5ae569dbd35b59f5596a61987cbcb25300411e71",
 "version": "0.1.8.post.dev13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
