# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: HHypermap Search
  description: Happy searching :)

#host: "localhost:8000" If the host is not included, the host serving the documentation is to be used (including the port).
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /registry/{catalog_slug}/api/:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      summary: Search/analytics endpoint; highly configurable. Not for bulk doc retrieval.
      description: The q. parameters qre query/constraints that limit the matching documents. The d. params control returning the documents. The a. params are faceting/aggregations on a field of the documents. The .limit params limit how many top values/docs to return. Some of the formatting and response structure has strong similarities with Apache Solr, unsurprisingly.
      # This is array of GET operation parameters:
      parameters:
        -
        # An example parameter that is in query and is required
          name: catalog_slug
          in: path
          description: Slug of catalog that needs to be fetched
          required: true
          type: string
          default: hypermap
        -
          name: q.time
          description: "Constrains docs by time range. Either side can be '*' to signify open-ended. Otherwise it must be in either format as given in the example. UTC time zone is implied."
          in: query
          required: false
          type: string
          x-example: "[1900-01-01 TO 2016-12-31T00:00:00]"
        -
          name: q.geo
          description: "A rectangular geospatial filter in decimal degrees going from the lower-left to the upper-right. The coordinates are in lat,lon format."
          in: query
          required: false
          type: string
          x-example: "[-90,-180 TO 90,180]"
        -
          name: q.text
          in: query
          description: Constrains docs by keyword search query.
          type: string
        -
          name: q.user
          in: query
          description: Constrains docs by matching exactly a certain user
          required: false
          type: string
        -
          name: d.docs.limit
          description: How many documents to return.
          in: query
          required: false
          type: integer
          default: 0
        -
          name: d.docs.page
          description: When documents to return are more than d.docs.limit they can be paginated by this value.
          in: query
          required: false
          type: integer
          default: 1
        -
          name: d.docs.sort
          description: "How to order the documents before returning the top X. 'score' is keyword search relevancy. 'time' is time descending. 'distance' is the distance between the doc and the middle of q.geo."
          in: query
          required: false
          type: string
          default: "score"
          enum: [ "score", "time", "distance" ]
        -
          name: a.time.limit
          description: "Non-0 triggers time/date range faceting. This value is the maximum number of time ranges to return when a.time.gap is unspecified. This is a soft maximum; less will usually be returned. A suggested value is 100. Note that a.time.gap effectively ignores this value. See Solr docs for more details on the query/response format."
          in: query
          required: false
          type: integer
          default: 0
        -
          name: a.time.gap
          description: "The consecutive time interval/gap for each time range. Ignores a.time.limit.The format is based on a subset of the ISO-8601 duration format."
          in: query
          required: false
          type: string
          default: "P1D"
        -
          name: a.time.filter
          description: From what time range to divide by a.time.gap into intervals. Defaults to q.time and otherwise 90 days.
          in: query
          required: false
          type: string
        -
          name: a.hm.limit
          description: "Non-0 triggers heatmap/grid faceting. This number is a soft maximum on thenumber of cells it should have. There may be as few as 1/4th this number in return. Note that a.hm.gridLevel can effectively ignore this value. The response heatmap contains a counts grid that can be null or contain null rows when all its values would be 0. See Solr docs for more details on the response format."
          in: query
          required: false
          type: integer
          default: 0
          maximum: 10000
          minimum: 0
        -
          name: a.hm.gridlevel
          description: "To explicitly specify the grid level, e.g. to let a user ask for greater or courser resolution than the most recent request.  Ignores a.hm.limit."
          in: query
          required: false
          type: integer
          default: 0
          maximum: 100
          minimum: 0
        -
          name: a.hm.filter
          description: From what region to plot the heatmap. Defaults to q.geo or otherwise the world.
          in: query
          required: false
          type: string
        -
          name: a.text.limit
          description: "Returns the most frequently occurring words. WARNING: There is usually a significant performance hit in this due to the extremely high cardinality."
          in: query
          required: false
          type: integer
          default: 0
        -
          name: a.user.limit
          description: Returns the most frequently occurring users.
          in: query
          required: false
          type: integer
          default: 0
        -
          name: original_response
          description: Just for debugging purposes when 1 will return the original solr response.
          in: query
          required: false
          type: integer
          default: 0
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Search Completed
          schema:
            $ref: '#/definitions/SearchResponse'
        400:
          description: Validation Errors
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'

  /registry/api/catalogs/:
    # This is a HTTP operation
    get:
      parameters:
      responses:
        # Response code
        200:
          description: An array of catalogs
  /registry/api/catalogs/{id}/:
    # This is a HTTP operation
    get:
      parameters:
        -
          name: id
          description: Get catalog detail by id
          in: path
          required: false
          type: integer
      responses:
        # Response code
        200:
          description: An array of catalogs
        404:
          description: Not found
definitions:
  HeatmapFacet:
    type: object
    properties:
      gridLevel:
        type: string
        format: int32
      rows:
        type: integer
        format: int32
      columns:
        type: integer
        format: int32
      minX:
        type: number
        format: double
      maxX:
        type: number
        format: double
      minY:
        type: number
        format: double
      maxY:
        type: number
        format: double
      counts_ints2D:
        type: array
        items:
          type: array
          items:
            type: integer
            format: int32
      projection:
        type: string
  FacetValue:
    type: object
    properties:
      value:
        type: string
      count:
        type: integer
        format: int64
  TimeFacet:
    type: object
    properties:
      start:
        type: string
      end:
        type: string
      gap:
        type: string
      counts:
        type: array
        items:
          $ref: '#/definitions/FacetValue'
  Timing:
    type: object
    properties:
      label:
        type: string
      millis:
        type: integer
        format: int64
      subs:
        type: array
        items:
          $ref: '#/definitions/Timing'
  SearchResponse:
    type: object
    properties:
      a.matchDocs:
        type: integer
        format: int64
      d.docs:
        type: array
        items:
          type: object
          additionalProperties:
            type: object
      a.time:
        $ref: '#/definitions/TimeFacet'
      a.hm:
        $ref: '#/definitions/HeatmapFacet'
      a.user:
        type: array
        items:
          $ref: '#/definitions/FacetValue'
      a.text:
        type: array
        items:
          $ref: '#/definitions/FacetValue'
      timing:
        $ref: '#/definitions/Timing'
  ErrorResponse:
    type: object
    properties:
      msg:
        type: string
      code:
        type: integer
      additionalProperties:
        type: object
