
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7267863c363c7d251ef9ab509779ed0af33bb1b7",
 "version": "0.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
