heat_template_version: 2015-04-30
description: 'OpenStack cinder storage post deployment for Puppet'

parameters:
  ConfigDebug:
    default: false
    description: Whether to run config management (e.g. Puppet) in debug mode.
    type: boolean
  servers:
    type: json
  DeployIdentifier:
     type: string
     description: Value which changes if the node configuration may need to be re-applied
  RoleData:
    type: json
    default: {}

resources:

  VolumeArtifactsConfig:
    type: deploy-artifacts.yaml

  VolumeArtifactsDeploy:
    type: OS::Heat::StructuredDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: VolumeArtifactsConfig}
      input_values:
        update_identifier: {get_param: DeployIdentifier}

  VolumePuppetConfig:
    type: OS::Heat::SoftwareConfig
    depends_on: VolumeArtifactsDeploy
    properties:
      group: puppet
      options:
        enable_debug: {get_param: ConfigDebug}
        enable_hiera: True
        enable_facter: False
        modulepath: /etc/puppet/modules:/opt/stack/puppet-modules:/usr/share/openstack-puppet/modules
      inputs:
      - name: step
      outputs:
      - name: result
      config:
        list_join:
        - ''
        - - get_file: manifests/overcloud_volume.pp
          - {get_param: [RoleData, step_config]}

  VolumeDeployment_Step2:
    type: OS::Heat::StructuredDeployments
    depends_on: VolumeArtifactsDeploy
    properties:
      name: VolumeDeployment_Step2
      servers:  {get_param: servers}
      config: {get_resource: VolumePuppetConfig}
      input_values:
        step: 2
        update_identifier: {get_param: DeployIdentifier}

  VolumeDeployment_Step3:
    type: OS::Heat::StructuredDeployments
    depends_on: VolumeDeployment_Step2
    properties:
      name: VolumeDeployment_Step3
      servers:  {get_param: servers}
      config: {get_resource: VolumePuppetConfig}
      input_values:
        step: 3
        update_identifier: {get_param: DeployIdentifier}

  VolumeDeployment_Step4:
    type: OS::Heat::StructuredDeployments
    depends_on: VolumeDeployment_Step3
    properties:
      name: VolumeDeployment_Step4
      servers:  {get_param: servers}
      config: {get_resource: VolumePuppetConfig}
      input_values:
        step: 4
        update_identifier: {get_param: DeployIdentifier}

  # Note, this should come last, so use depends_on to ensure
  # this is created after any other resources.
  ExtraConfig:
    depends_on: VolumeDeployment_Step4
    type: OS::TripleO::NodeExtraConfigPost
    properties:
        servers: {get_param: servers}
