
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.4'
version_full = 'e0511fa77e3ae9ab3c13c427c1cc55331e149ac2'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

