
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6d90cc18029252608c6e7dfd1bf9f2612fbc4cd1",
 "version": "0.7.post8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
