# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import uuid
import os


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=os.path.join(settings.BASE_DIR, 'generated'))),
                ('text', models.TextField()),
                ('command', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('wav', 'wav')], max_length=5)),
                ('dc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
