
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7b098ead05e0dc2508b39e71d0715c8ad04595e1",
 "version": "1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
