
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.2.0'
version_full = '438a1d50091381c57f1b75afef32850d0d623cd0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

