
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bae668d92da02cd4b2e2f58eeeeae0d3599e7bfb",
 "version": "1.0.51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
