"""
Default configuration settings.
"""

# TODO: Get rid of units in setting names


CORALOGIX_API_ENDPOINT = 'https://api.coralogix.com/sdk/v1' # Coralogix server URL

BULK_TIME_IN_MILLI_THRESHOLD = 1000

BULK_SIZE_IN_KIB_THRESHOLD = 500

IS_ACTIVE = True # Should the SDK send logs to Coralogix?

IS_PRODUCTION_MODE = True # Should internal logging be verbose? If True, only errors will be logged.

BUFFER_MAX_SIZE_IN_KIB = 4000

AUTHENTICATION_RETRIES = FLUSH_RETRIES = 3

PERCENTAGE_OF_BUFFER_NORMAL_COMPLETENESS = 50

INTERVAL_IN_MILLI_FOR_TIMER_ON_DISCONNECTION = 5000

LOG_PERFORMANCE_DATA_INTERVAL = 30000 # ms

RELOAD_CONFIG_INTERVAL = 120000 # ms

INTERVAL_IN_MILLI_TO_FLUSH_LOCAL_LOG = 5000

INTERVAL_IN_MILLI_TO_SLEEP_BETWEEN_RETRIES = 200

INTERVAL_IN_MILLI_TO_START_TRYING_TO_RECONNECT = 2000

TIMEOUT_IN_MILLI_FOR_REQUESTS = 5000

INNER_LOG_FILE_MAX_SIZE_IN_KIB = 2000

INTERVAL_IN_MILLI_TO_SYNC_CORALOGIX_TIME = 30000

APPLICATION_NAME = ''

SUBSYSTEM_NAME = ''
