
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ce902e098dc12f01b8062afa0b469c22519e46ba",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
