#config_version=4
mode:
  code: high_score.HighScore
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true

# Instructions on how to use this mode:
# https://missionpinball.com/docs/howto/high-scores/

# You can copy the sections below to your own machine config as a starting point


#high_score:
#  shift_left_tag: left_flipper
#  shift_right_tag: right_flipper
#  select_tag: start
#  award_slide_display_time: 4s
#  categories:
#  - score:
#      - GRAND CHAMPION
#      - HIGH SCORE 1
#      - HIGH SCORE 2
#      - HIGH SCORE 3
#      - HIGH SCORE 4

# Be sure to put this slide_player config in your modes/high_score folder, not your
# machine-wide config, because you want it to run at the priority of the mode

#slide_player:
#  high_score:
#    - type: text
#      text: PLAYER %player_num%
#      font: medium
#      v_pos: bottom
#      h_pos: center
#      x: -27
#      y: -21
#    - type: text
#      text: "%award%"
#      font: small
#      v_pos: bottom
#      h_pos: center
#      x: -27
#      y: -12
#    - type: character_picker
#      name: high_score
#      slide_name: high_score
#      clear_slide: true
#      persist: no
#      height: 9
#      font: medium
#      v_pos: bottom
#      selected_char_color: 0
#      selected_char_bg: 15
#      char_x_offset: 1
#      char_y_offset: 1
#      char_width: 7
#      char_list: "ABCDEFGHIJKLMNOPQRSTUVWXYZ_- "
#      back_char: back_arrow_7x7
#      end_char: end_11x7
#      back_char_selected: back_arrow_7x7_selected
#      end_char_selected: end_11x7_selected
#      image_padding: 1
#      shift_left_tag: left_flipper
#      shift_right_tag: right_flipper
#      select_tag: start
#      max_chars: 3
#      timeout: 30s
#      return_param: award
#
#    - type: entered_chars
#      character_picker: high_score
#      cursor_char: _
#      v_pos: bottom
#      h_pos: left
#      x: 90
#      y: -12
#      cursor_offset_x: 0
#      cursor_offset_y: 0
#      cursor_decorators:
#        type: blink
#
#  high_score_award_display:
#    - type: text
#      text: "%player_name%"
#      color: 0
#      bg_color: 15
#      v_pos: center
#      y: 2
#      decorators:
#        type: blink
#        on_secs: .05
#        off_secs: .05
#    - type: text
#      text: "%award%"
#      font: medium
#      v_pos: top
#      y: 2
