# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_memdb.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelPersistent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            bases=(models.Model, django_memdb.mixins.PeristentInMemoryDB),
        ),
        migrations.CreateModel(
            name='TestModelWithMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            bases=(models.Model, django_memdb.mixins.InMemoryDB),
        ),
    ]
