# A Heat environment file which can be used to enable a
# a Manila generic driver backend.
resource_registry:
  OS::Tripleo::Services::ManilaApi: ../puppet/services/manila-api.yaml
  OS::Tripleo::Services::ManilaScheduler: ../puppet/services/manila-scheduler.yaml
  # Only manila-share is pacemaker managed:
  OS::Tripleo::Services::ManilaShare: ../puppet/services/pacemaker/manila-share.yaml


parameter_defaults:
  ManilaGenericEnableBackend: true
  ManilaGenericBackendName: tripleo_generic
  ManilaGenericDriverHandlesShareServers: true
  ManilaGenericSmbTemplateConfigPath: '$state_path/smb.conf'
  ManilaGenericVolumeNameTemplate: 'manila-share-%s'
  ManilaGenericVolumeSnapshotNameTemplate: 'manila-snapshot-%s'
  ManilaGenericShareMountPath: '/shares'
  ManilaGenericMaxTimeToCreateVolume: '180'
  ManilaGenericMaxTimeToAttach: '120'
  ManilaGenericServiceInstanceSmbConfigPath: '$share_mount_path/smb.conf'
  ManilaGenericShareVolumeFsType: 'ext4'
  ManilaGenericCinderVolumeType: ''
  ManilaGenericServiceInstanceUser: ''
  ManilaGenericServiceInstancePassword: ''
  ManilaGenericServiceInstanceFlavorId: 2
  ManilaGenericServiceNetworkCidr: '172.16.0.0/16'
