from telethon.tl.mtproto_request import MTProtoRequest


class GetArchivedStickersRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messages.getArchivedStickers#906e241f offset_id:long limit:int = messages.ArchivedStickers"""

    def __init__(self, offset_id, limit):
        """
        :param offset_id: Telegram type: «long».
        :param limit: Telegram type: «int».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x906e241f

        self.offset_id = offset_id
        self.limit = limit

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.write_long(self.offset_id)
        writer.write_int(self.limit)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'messages.getArchivedStickers#906e241f offset_id:long limit:int = messages.ArchivedStickers'

    def __str__(self):
        return '(messages.getArchivedStickers (ID: 0x906e241f) = (offset_id={}, limit={}))'.format(str(self.offset_id), str(self.limit))
