
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f80a654a2edb44451a2b4b6e4c20681220f15f64",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
