heat_template_version: 2016-04-08

description: >
  Horizon service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  HorizonAllowedHosts:
    default: '*'
    description: A list of IP/Hostname allowed to connect to horizon
    type: comma_delimited_list
  NeutronMechanismDrivers:
    default: 'openvswitch'
    description: |
        The mechanism drivers for the Neutron tenant network.
    type: comma_delimited_list

outputs:
  role_data:
    description: Role data for the Horizon role.
    value:
      service_name: horizon
      config_settings:
        horizon::allowed_hosts: {get_param: HorizonAllowedHosts}
        neutron::plugins::ml2::mechanism_drivers:
          str_replace:
            template: MECHANISMS
            params:
              MECHANISMS: {get_param: NeutronMechanismDrivers}
        tripleo.horizon.firewall_rules:
          '126 horizon':
            dport:
              - 80
              - 443
        horizon::cache_backend: django.core.cache.backends.memcached.MemcachedCache
        horizon::django_session_engine: 'django.contrib.sessions.backends.cache'
        horizon::vhost_extra_params:
          add_listen: false
          priority: 10
          access_log_format: '%a %l %u %t \"%r\" %>s %b \"%%{}{Referer}i\" \"%%{}{User-Agent}i\"'
      step_config: |
        include ::tripleo::profile::base::horizon
