
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "630e886123f8f6b14a2f65be85b7d083acfc60ae",
 "version": "0.1.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
