# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('sku_code', models.CharField(max_length=255)),
                ('dc', models.DateTimeField(auto_now_add=True)),
                ('extra', models.TextField(help_text='json-объект с дополнительным описанием')),
                ('cost', models.DecimalField(blank=True, max_digits=14, decimal_places=4, help_text='Стоимость, по которой была оказана услуга (заполняется в ходе вхаимодействия с CRM)', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='billing.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('sum', models.DecimalField(blank=True, max_digits=14, decimal_places=4, help_text='сумма платежа', null=True)),
                ('dc', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.Customer')),
            ],
        ),
    ]
