
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "81055071062383e2b03368ac0d473f5a10aa24a3",
 "version": "0.1.8.post.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
