#
# Config file for Variant Calling
#
##############################################################################

# =========================================== Sections for the users

# List of your input file
samples:
    file1: "%(file1)s"
    file2: "%(file2)s"

# Project name
project: "%(project)s"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ GenomeAnalysisTK

# GATK is absent in conda because it is not a free software
# You must set the GATK bin path.
# gatk_bin: "java -jar /path/to/GenomeAnalysisTK.jar"

gatk_bin: GenomeAnalysisTK

# =========================================== Sections related to variant calling

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Bwa

bwa_ref:
    reference: "%(reference)s"  # Genome of reference
    index:      # Options for bwa index
        options: '-a is'
    mem:        # Options for bwa mem
        options: '-T 30'
        # -R option for GATK
        read_groups: '@RG\\tID:1\\tSM:1\\tPL:illumina'
        # -t option (number thread)
        threads: 2 

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SnpEff

#Results filter options:
#	-no-downstream: Do not show DOWNSTREAM changes
#	-no-intergenic: Do not show INTERGENIC changes
#	-no-intron: Do not show INTRON changes
#	-no-upstream: Do not show UPSTREAM changes
#	-no-utr: Do not show 5_PRIME_UTR or 3_PRIME_UTR changes
snpeff:
    do: no
    reference:
    format: ""      # format of your annotation file (genbank/gff)
    options: "-no-downstream -no-upstream"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Bedtools genomecov

bedtools: 
    options: '-d'

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Freebayes

freebayes:
    options: '--ploidy 1'

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Indel realigner (GATK)

indel_realigner:
    do: yes
    options: ''

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Mark duplicates (picard-tools)

mark_duplicates:
    do: yes
    options: ''

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Report Mapping

report_mapping:
    do: yes
    k: 2                      # Number of gaussian predicted
    circular: no              # If your genome is circular
    window_size: 30001        # Window size for compute the running median
    first_threshold: 4        # Primary threshold to detect high/low coverage regions 
    second_threshold: 2       # Secondary threshold to detect high/low coverage regions

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ VCF filter (dedicated to freebayes)

# You can add other filter options in INFO field.
# All possible fields are showed at the start of a vcf file generated by freebayes.

vcf_filter:
    QUAL: 1000              # Freebayes score
    FREQ: 0.8               # Alternative allele frequency
    INFO:
        DP: '>= 10'         # Coverage depth per base
