
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "347ee3894281cdfc316b2cd0dc566ae9b948fbe7",
 "version": "1.0.0.post.dev209"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
