
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.14.0'
version_full = '2dad935106b4ad224d9175ccefe8e265ef6be6b8'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

