
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "60a38a2b4d297e6fe462b4a73e3d1fea1b7b5d28",
 "version": "0.0.0a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
