
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c05c76caf94bcbec7ec6bb1af09758443b95cf83",
 "version": "0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
