
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "97d0c8be81c7bcfbdd1091787f76175c0a560709",
 "version": "0.12.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
