
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "427fa28943d6a79a9f9566ee5fd1998230f1d0a6",
 "version": "0.post.dev37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
