
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e387c29e84dc0376febcd9856d0a9247287b4f1e",
 "version": "2016.0829.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
