from telethon.tl.mtproto_request import MTProtoRequest


class GetAppUpdateRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    help.getAppUpdate#ae2de196  = help.AppUpdate"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0xae2de196

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'help.getAppUpdate#ae2de196  = help.AppUpdate'

    def __str__(self):
        return '(help.getAppUpdate (ID: 0xae2de196) = ())'.format()
