from telethon.tl.mtproto_request import MTProtoRequest


class GetTermsOfServiceRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    help.getTermsOfService#350170f3  = help.TermsOfService"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x350170f3

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'help.getTermsOfService#350170f3  = help.TermsOfService'

    def __str__(self):
        return '(help.getTermsOfService (ID: 0x350170f3) = ())'.format()
