from telethon.tl.mtproto_request import MTProtoRequest


class GetNearestDcRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    help.getNearestDc#1fb33026  = NearestDc"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x1fb33026

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'help.getNearestDc#1fb33026  = NearestDc'

    def __str__(self):
        return '(help.getNearestDc (ID: 0x1fb33026) = ())'.format()
