from telethon.tl.mtproto_request import MTProtoRequest


class GetConfigRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    help.getConfig#c4f9186b  = Config"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0xc4f9186b

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'help.getConfig#c4f9186b  = Config'

    def __str__(self):
        return '(help.getConfig (ID: 0xc4f9186b) = ())'.format()
