---
- name: Install NFS
  yum:
    name: nfs-utils
    state: present

- name: Create registry share
  file:
    path:  /var/exports/registry
    state: directory
    owner: nfsnobody
    group: nfsnobody
    mode:  0777
  delegate_to: "{{ groups['k8sdc-master'][0] }}"
  run_once: yes

- name: Copy exports file
  copy:
    src:  exports
    dest: /etc/exports
  delegate_to: "{{ groups['k8sdc-master'][0] }}"
  run_once: yes

- name: Ensure rpcbind is enabled and running
  service:
    name:    rpcbind
    enabled: yes
    state:   running

- name: Restart nfs
  service:
    name:  nfs
    state: restarted
  delegate_to: "{{ groups['k8sdc-master'][0] }}"
  run_once: yes