heat_template_version: 2016-04-08

description: Sensu client configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: >
      Mapping of service endpoint -> protocol. Typically set
      via parameter_defaults in the resource registry.
    type: json
  SensuClientCustomConfig:
    default: {}
    description: Hash containing custom sensu-client variables.
    type: json
    label: Custom configuration for Sensu Client variables

resources:
  SensuBase:
    type: ./sensu-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Sensu client role.
    value:
      service_name: sensu_client
      monitoring_subscription: all
      config_settings:
        map_merge:
          - get_attr: [SensuBase, role_data, config_settings]
          - sensu::api: false
            sensu::client: true
            sensu::server: false
            sensu::client_custom: {get_param: SensuClientCustomConfig}
      step_config: |
        include ::tripleo::profile::base::monitoring::sensu
