
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cc13b0bf3970318f7db24b830cffccc9ae252c90",
 "version": "0.2.post48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
