
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "630d71bae8238ba533932b5a6201e9b0c0c30117",
 "version": "1.0.0.post.dev211"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
