
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "da16fcf3cf36e3f1e9ab01b12e2f9839e41f6500",
 "version": "v1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
