sudo: false
language: python
python:
- 2.7
- 3.5
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
before_deploy:
- pip install https://dl.dropboxusercontent.com/u/54081/cheeseshop/setuptools_scm-1.14.1b1.tar.gz
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  distributions: dists
  password:
    secure: oIhtmrYfC6YLIpQtrdaehuhso5PkwH44MyvJbKfysWpud+Cq8bhapfEDj7ljhsyPaBUtuTjJr8VSIuYyvxlgZmfO0PIG4ZlYaKmwMfHF0PdPjqgEx2Ap7ptgRzBfXC0VPSVulR4bWdYimgZ3AxZufrnUfnVR5enmr7SOZZ2TIWhFpAo5RCZ2i5TZi72VHEfrRFaM27u2wgTcVOvWEH5yR4O60i4u+bKujyDz1bjZWdrGbY78ZbJvzyYRZNCMaalUp5PAk58MHLGXUX4E6e12x2lA1hbg0FQl1eY2R5VkbSdIsZJ43l6DGsU29mY7kKgvrhU17z3QyOitSAAzuy579Agdm+Ajdby4r01b9TfSyImK5Ci7PlbiGOGSVPAB+fGsZYHGZe0pJ/XWqTTPWK/zLwLctEDCBLlvrabCZvYnykzu0G4kUXQnxczW30Qm5XBdQ1mNGxhTldFmUM8Gm5LLTPW/SE4Slr7PUHvCpf0sLteDgtRJWGzm7VTZvVFqh62WytoV8dKJvBj3F4BZgncLiSQVae7HFWTwKOvzLMUlI2oDgehYLOwEg7PIKFAsPTzrV5RC5PLzahAzcmi8C5yHh2JVchwqJhjXxQTCE6zYM7PegbhNTWINjR5OdFZxZa9/dsRVaNSCGD1D+SEHg8rgXa1a1NLL3h3qdHOk4SQMohI=
