
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.1'
version_full = 'bb4ab9358057f63dee647a74bedd063615596604'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

