codecov:
  branch: master
  bot: sebastianstigler

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: true

    patch: true

    changes: True

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
