# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMeow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default=b'')),
                ('keywords', models.TextField(blank=True, default=b'')),
            ],
            options={
                'ordering': ('url', 'pk'),
                'db_table': 'seomeow',
            },
        ),
    ]
