# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seomeow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seomeow',
            options={'ordering': ('url', 'modified', 'pk')},
        ),
        migrations.AddField(
            model_name='seomeow',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 31, 9, 14, 18, 437000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
