# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seomeow', '0002_auto_20160831_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seomeow',
            options={'ordering': ('url', 'pk'), 'verbose_name': 'seo-meow tags', 'verbose_name_plural': 'seo-meow'},
        ),
    ]
