
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1b39989f846f8f9ce0fe135d4c9c9871dc88205b",
 "version": "0.12.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
