from telethon.tl.mtproto_request import MTProtoRequest


class DhConfig(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messages.dhConfig#2c221edd g:int p:bytes version:int random:bytes = messages.DhConfig"""

    def __init__(self, g, p, version, random):
        """
        :param g: Telegram type: «int».
        :param p: Telegram type: «bytes».
        :param version: Telegram type: «int».
        :param random: Telegram type: «bytes».
        """
        super().__init__()
        self.constructor_id = 0x2c221edd

        self.g = g
        self.p = p
        self.version = version
        self.random = random

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.write_int(self.g)
        writer.tgwrite_bytes(self.p)
        writer.write_int(self.version)
        writer.tgwrite_bytes(self.random)

    def on_response(self, reader):
        self.g = reader.read_int()
        self.p = reader.tgread_bytes()
        self.version = reader.read_int()
        self.random = reader.tgread_bytes()

    def __repr__(self):
        return 'messages.dhConfig#2c221edd g:int p:bytes version:int random:bytes = messages.DhConfig'

    def __str__(self):
        return '(messages.dhConfig (ID: 0x2c221edd) = (g={}, p={}, version={}, random={}))'.format(str(self.g), str(self.p), str(self.version), str(self.random))
