# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='draft_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='blog.Blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='has_draft',
            field=models.BooleanField(default=False, verbose_name='Has draft'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is draft'),
        ),
    ]
