# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160930_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='draft_of',
        ),
        migrations.RemoveField(
            model_name='category',
            name='has_draft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_draft',
        ),
    ]
