sudo: false
cache: pip

language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - TOXENV=manifest
    - TOXENV=docs

matrix:
    include:
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35

before_install:
    - pip install codecov

install:
    - pip install tox

script:
    - tox

after_success:
    - tox -e coverage-report
    - codecov

notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq

addons:
    code_climate:
        repo_token: e8d763f60ca5495b8bce79682b7c1e2e462a776f8de5c4540ceb01f52458f891
