from telethon.tl.mtproto_request import MTProtoRequest


class CheckPhoneRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    auth.checkPhone#6fe51dfb phone_number:string = auth.CheckedPhone"""

    def __init__(self, phone_number):
        """
        :param phone_number: Telegram type: «string».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x6fe51dfb

        self.phone_number = phone_number

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_string(self.phone_number)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'auth.checkPhone#6fe51dfb phone_number:string = auth.CheckedPhone'

    def __str__(self):
        return '(auth.checkPhone (ID: 0x6fe51dfb) = (phone_number={}))'.format(str(self.phone_number))
