from telethon.tl.mtproto_request import MTProtoRequest


class RequestPasswordRecoveryRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    auth.requestPasswordRecovery#d897bc66  = auth.PasswordRecovery"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0xd897bc66

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'auth.requestPasswordRecovery#d897bc66  = auth.PasswordRecovery'

    def __str__(self):
        return '(auth.requestPasswordRecovery (ID: 0xd897bc66) = ())'.format()
