from telethon.tl.mtproto_request import MTProtoRequest


class ResetAuthorizationsRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    auth.resetAuthorizations#9fab0d1a  = Bool"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x9fab0d1a

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'auth.resetAuthorizations#9fab0d1a  = Bool'

    def __str__(self):
        return '(auth.resetAuthorizations (ID: 0x9fab0d1a) = ())'.format()
