language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
install:
- pip install pip --upgrade
- pip install setuptools --upgrade
- pip install --install-option='--no-cython-compile' cython
- pip install numpy
- pip install bcolz
- python setup.py build_ext --inplace
script:
- nosetests bquery
notifications:
email: false
