
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a40900e62e2ce5f0f51ea1751ef72258c8de7c64",
 "version": "1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
