
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-10-12T16:09:00+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "6a55fd161e95e1d38b11df848f8ce195cd9e2510",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
