from telethon.tl.mtproto_request import MTProtoRequest


class GetSupportRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    help.getSupport#9cdf08cd  = help.Support"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x9cdf08cd

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'help.getSupport#9cdf08cd  = help.Support'

    def __str__(self):
        return '(help.getSupport (ID: 0x9cdf08cd) = ())'.format()
