
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5e4689ee3a1852bd6f71ea59cefdc6c8b8934481",
 "version": "0.1.8.post.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
