
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.5'
version_full = '32bc4f1a960d2104e779f17339424dd316520e50'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

