
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "36a9f43897280cb82220508fe0cafe22f0f24ab5",
 "version": "0.4.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
