# variables in header
x-openstack-request-id:
  description: >
    A unique ID for tracking the request. The request ID associated with the request
    appears in the log lines for that request. By default, the middleware configuration
    ensures that the request ID appears in the log files.
  in: header
  required: true
  type: string
x-openstack-request-id_1:
  description: |
    A unique request ID that provides tracking for the request. Provider must configure
    middleware to return a request ID header in a response.
  in: header
  required: false
  type: string

# variables in path
port_chain_id:
  description: |
      The UUID of the port-chain.
  in: path
  required: true
  type: uuid

# variables in query

# variables in body
chain_id:
  description: |
      The UUID of the port-chain.
  in: body
  required: true
  type: uuid
chain_parameters:
  description: |
    A dictionary of chain parameters.
  in: body
  required: false
  type: dict
classifier_name:
  description: |
      The name of the flow-classifier.
  in: body
  required: true
  type: string
description:
  description: |
      Text describing this parameter.
  in: body
  required: false
  type: string
destination_ip_prefix:
  description: |
    The destination IP prefix.
  in: body
  required: false
  type: cidr
destination_logical_port:
  description: |
    The UUID of the destination logical port.
  in: body
  required: false
  type: uuid
destination_port_range_max:
  description: |
    Maximum destination protocol port.
  in: body
  required: false
  type: integer
destination_port_range_min:
  description: |
    Minimum destination protocol port.
  in: body
  required: false
  type: integer
egress_port_id:
  description: |
    The UUID of the egress Neutron port.
  in: body
  required: true
  type: uuid
ethertype:
  description: |
    L2 ethertype. Can be IPv4 or IPv6 only.
  in: body
  required: false
  type: string
flow_classifier_id:
  description: |
      The UUID of the flow-classifier.
  in: body
  required: true
  type: uuid
flow_classifiers:
  description: |
      List of flow-classifier UUIDs.
  in: body
  required: false
  type: list(uuid)
ingress_port_id:
  description: |
    The UUID of the ingress Neutron port.
  in: body
  required: true
  type: uuid
l7_parameters:
  description: |
    A dictionary of L7 parameters.
  in: body
  required: false
  type: dict
port_chain_name:
  description: |
      The name of the port-chain.
  in: body
  required: true
  type: string
port_pair_group_id:
  description: |
      The UUID of the port-pair-group.
  in: body
  required: true
  type: uuid
port_pair_group_name:
  description: |
      The name of the port-pair-group.
  in: body
  required: true
  type: string
port_pair_groups:
  description: |
      List of port-pair-group UUIDs.
  in: body
  required: true
  type: list(uuid)
port_pair_id:
  description: |
      The UUID of the port-pair.
  in: body
  required: true
  type: uuid
port_pair_name:
  description: |
      The name of the port-pair.
  in: body
  required: true
  type: string
port_pairs:
  description: |
      List of port-pair UUIDs.
  in: body
  required: true
  type: list(uuid)
protocol:
  description: |
    IP protocol.
  in: body
  required: false
  type: string
service_function_parameters:
  description: |
    A dictionary of service function parameters.
  in: body
  required: false
  type: dict
source_ip_prefix:
  description: |
    The source IP prefix.
  in: body
  required: false
  type: cidr
source_logical_port:
  description: |
    The UUID of the source logical port.
  in: body
  required: false
  type: uuid
source_port_range_max:
  description: |
    Maximum source protocol port.
  in: body
  required: false
  type: integer
source_port_range_min:
  description: |
    Minimum source protocol port.
  in: body
  required: false
  type: integer
tenant_id:
  description: |
     The UUID of the tenant in a multi-tenancy cloud.
  in: body
  required: true
  type: uuid

