bind:
  address: "0.0.0.0"
  port: 8080
auth: # HTTP authentication, could be nothing
  enable: False
  username: ""
  password: ""
proxy: # Keys and values must match the omega rule
  profile:
    first: "http://username:password@127.0.0.1:12345" # "username:password@" could be nothing
    second: "socks5://127.0.0.1:23456"
    direct: "direct://"
    filter: "filter://" # Define "filter" as the filter profile name for "filter://", you can rename it as you want
  virtual: # Virtual profile as alias
    speed: "first"
omega_file: "omega.conf"
filter:
  china_ip_list_file: "china_ip_list.txt" # From https://github.com/17mon/china_ip_list
  filter_profile: "first" # Profile to use for foreign host
ipv6_test:
  force_family: "auto" # ipv4, ipv6, auto
  host: "www.yahoo.com"
  port: 443
process_num: 0 # Number of process to run, 0 for auto
tcp_keep_alive: False
short_request_keyword_list: # Force to use short request when header's host has one of these keywords
  - "ifeng" # Fix 302 location error
  - "youku"