
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "149a734e62e3731d4f25d811cd4ecac2142d9f25",
 "version": "0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
