from telethon.tl.mtproto_request import MTProtoRequest


class AppChangelog(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    help.appChangelog#4668e6bd text:string = help.AppChangelog"""

    def __init__(self, text):
        """
        :param text: Telegram type: «string».
        """
        super().__init__()
        self.constructor_id = 0x4668e6bd

        self.text = text

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_string(self.text)

    def on_response(self, reader):
        self.text = reader.tgread_string()

    def __repr__(self):
        return 'help.appChangelog#4668e6bd text:string = help.AppChangelog'

    def __str__(self):
        return '(help.appChangelog (ID: 0x4668e6bd) = (text={}))'.format(str(self.text))
