package:
  name: shot-detector
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}"

source:
  git_url: ../

build:
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}
  detect_binary_files_with_prefix: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyav

about:
  home: https://pypi.python.org/pypi/shot-detector
  license: BSD
  license_file: LICENSE.txt
