
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c8b24f0d066e0788b7619910611ee235d22533db",
 "version": "0.12.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
