
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4c1aeae66b3353ce1331d30b8384651786890137",
 "version": "1.0.54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
