
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.0b1'
version_full = '5cfe2399e8579b3b5a3fc8a4d141a4ded09d1a6b'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

