
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8ef265bc7d35fa3047e9caeb5b1728cb5b1f8f36",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
