
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "83d12b7f851cf1d4c832fc728a39183baa75fdbc",
 "version": "1.2.57"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
