language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements_travis.txt
  - pip install -r requirements_test.txt

script:
  - coverage run -m py.test

after_success:
  - coveralls