language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

# command to install dependencies
install:
  - python -m pip install -U pip
  - python -m pip install -U setuptools
  - pip install .

# command to run tests
script: python setup.py test
