
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.1'
version_full = 'd2fc2556af3992f5833ad8c9aa182207033a8260'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

