
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e4d91a9945a6bbe75d61aff0c378003fa8c3a437",
 "version": "v0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
