transport_name: smpp_transport
system_id: wel2wiki  # username
password: wiki2wel      # password
host: 41.223.58.132         # the host to connect to
# host: 127.0.0.1
port: 31110              # the port to connect to
