"""
Defines constant constraints on configuration settings.
"""

MIN_BULK_TIME_IN_MILLI_THRESHOLD = 500
MAX_BULK_TIME_IN_MILLI_THRESHOLD = 25000

MIN_BULK_SIZE_IN_KIB_THRESHOLD = 100
MAX_BULK_SIZE_IN_KIB_THRESHOLD = 1000

MIN_BUFFER_MAX_SIZE_IN_KIB = 1000
MAX_BUFFER_MAX_SIZE_IN_KIB = 10000

MIN_AUTHENTICATION_RETRIES = MIN_FLUSH_RETRIES = 0
MAX_AUTHENTICATION_RETRIES = MAX_FLUSH_RETRIES = 10

MIN_PERCENTAGE_OF_BUFFER_NORMAL_COMPLETENESS = 25
MAX_PERCENTAGE_OF_BUFFER_NORMAL_COMPLETENESS = 80

MIN_INTERVAL_IN_MILLI_FOR_TIMER_ON_DISCONNECTION = 5000
MAX_INTERVAL_IN_MILLI_FOR_TIMER_ON_DISCONNECTION = 120000

MIN_LOG_PERFORMANCE_DATA_INTERVAL = 2000
MAX_LOG_PERFORMANCE_DATA_INTERVAL = 360000

MIN_RELOAD_CONFIG_INTERVAL = 20000
MAX_RELOAD_CONFIG_INTERVAL = 150000

MIN_INTERVAL_IN_MILLI_TO_FLUSH_LOCAL_LOG = 2000
MAX_INTERVAL_IN_MILLI_TO_FLUSH_LOCAL_LOG = 10000

MIN_INTERVAL_IN_MILLI_TO_SLEEP_BETWEEN_RETRIES = 100
MAX_INTERVAL_IN_MILLI_TO_SLEEP_BETWEEN_RETRIES = 1000

MIN_INTERVAL_IN_MILLI_TO_START_TRYING_TO_RECONNECT = 2000
MAX_INTERVAL_IN_MILLI_TO_START_TRYING_TO_RECONNECT = 10000

MIN_TIMEOUT_IN_MILLI_FOR_REQUESTS = 5000
MAX_TIMEOUT_IN_MILLI_FOR_REQUESTS = 30000

MIN_INNER_LOG_FILE_MAX_SIZE_IN_KIB = 1000
MAX_INNER_LOG_FILE_MAX_SIZE_IN_KIB = 10000

MIN_INTERAL_IN_MILLI_TO_SYNC_CORALOGIX_TIME = 5000
MAX_INTERAL_IN_MILLI_TO_SYNC_CORALOGIX_TIME = 60000
