# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainView.ui'
#
# Created: Mon Mar  5 11:52:52 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(401, 494)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outline = QtGui.QTreeView(self.centralwidget)
        self.outline.setObjectName("outline")
        self.outline.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.outline)
        self.widgetStack = QtGui.QStackedWidget(self.centralwidget)
        self.widgetStack.setObjectName("widgetStack")
        self.addSet = QtGui.QWidget()
        self.addSet.setObjectName("addSet")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.addSet)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.addSet)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.newSetName = QtGui.QLineEdit(self.addSet)
        self.newSetName.setObjectName("newSetName")
        self.horizontalLayout_3.addWidget(self.newSetName)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtGui.QLabel(self.addSet)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.layoutChooserAddSet = QtGui.QComboBox(self.addSet)
        self.layoutChooserAddSet.setObjectName("layoutChooserAddSet")
        self.horizontalLayout.addWidget(self.layoutChooserAddSet)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.setDefaultLayout = QtGui.QCheckBox(self.addSet)
        self.setDefaultLayout.setObjectName("setDefaultLayout")
        self.verticalLayout_3.addWidget(self.setDefaultLayout)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.createSetButton = QtGui.QPushButton(self.addSet)
        self.createSetButton.setObjectName("createSetButton")
        self.verticalLayout_11.addWidget(self.createSetButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.previewAddSet = LayoutPreview(self.addSet)
        self.previewAddSet.setMinimumSize(QtCore.QSize(100, 0))
        self.previewAddSet.setObjectName("previewAddSet")
        self.horizontalLayout_6.addWidget(self.previewAddSet)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.widgetStack.addWidget(self.addSet)
        self.editSet = QtGui.QWidget()
        self.editSet.setObjectName("editSet")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.editSet)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.previewEditSet = LayoutPreview(self.editSet)
        self.previewEditSet.setObjectName("previewEditSet")
        self.verticalLayout_20.addWidget(self.previewEditSet)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.layoutChooserEditSet = QtGui.QComboBox(self.editSet)
        self.layoutChooserEditSet.setObjectName("layoutChooserEditSet")
        self.horizontalLayout_7.addWidget(self.layoutChooserEditSet)
        self.setLayoutButton = QtGui.QPushButton(self.editSet)
        self.setLayoutButton.setObjectName("setLayoutButton")
        self.horizontalLayout_7.addWidget(self.setLayoutButton)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_20.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.removeSetButton = QtGui.QPushButton(self.editSet)
        self.removeSetButton.setObjectName("removeSetButton")
        self.horizontalLayout_20.addWidget(self.removeSetButton)
        self.addAudioButton = QtGui.QPushButton(self.editSet)
        self.addAudioButton.setObjectName("addAudioButton")
        self.horizontalLayout_20.addWidget(self.addAudioButton)
        self.verticalLayout_20.addLayout(self.horizontalLayout_20)
        self.verticalLayout_20.setStretch(0, 5)
        self.verticalLayout_20.setStretch(1, 1)
        self.verticalLayout_20.setStretch(2, 1)
        self.widgetStack.addWidget(self.editSet)
        self.editContainer = QtGui.QWidget()
        self.editContainer.setObjectName("editContainer")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.editContainer)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.containerTabs = QtGui.QTabWidget(self.editContainer)
        self.containerTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.containerTabs.setObjectName("containerTabs")
        self.fileDialog = QtGui.QWidget()
        self.fileDialog.setObjectName("fileDialog")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.fileDialog)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.containerName = QtGui.QLabel(self.fileDialog)
        self.containerName.setObjectName("containerName")
        self.verticalLayout.addWidget(self.containerName)
        self.containerStatus = QtGui.QLabel(self.fileDialog)
        self.containerStatus.setObjectName("containerStatus")
        self.verticalLayout.addWidget(self.containerStatus)
        self.checkBox = QtGui.QCheckBox(self.fileDialog)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.addFileButton = QtGui.QPushButton(self.fileDialog)
        self.addFileButton.setObjectName("addFileButton")
        self.verticalLayout.addWidget(self.addFileButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.previewContainer = LayoutPreview(self.fileDialog)
        self.previewContainer.setObjectName("previewContainer")
        self.horizontalLayout_4.addWidget(self.previewContainer)
        self.containerTabs.addTab(self.fileDialog, "")
        self.syncDialog = QtGui.QWidget()
        self.syncDialog.setObjectName("syncDialog")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.syncDialog)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.changeSyncButton = QtGui.QPushButton(self.syncDialog)
        self.changeSyncButton.setObjectName("changeSyncButton")
        self.verticalLayout_8.addWidget(self.changeSyncButton)
        self.verifyButton = QtGui.QPushButton(self.syncDialog)
        self.verifyButton.setObjectName("verifyButton")
        self.verticalLayout_8.addWidget(self.verifyButton)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.event1pic = QtGui.QLabel(self.syncDialog)
        self.event1pic.setObjectName("event1pic")
        self.verticalLayout_7.addWidget(self.event1pic)
        self.event1text = QtGui.QLabel(self.syncDialog)
        self.event1text.setObjectName("event1text")
        self.verticalLayout_7.addWidget(self.event1text)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.event2pic = QtGui.QLabel(self.syncDialog)
        self.event2pic.setObjectName("event2pic")
        self.verticalLayout_9.addWidget(self.event2pic)
        self.event2text = QtGui.QLabel(self.syncDialog)
        self.event2text.setObjectName("event2text")
        self.verticalLayout_9.addWidget(self.event2text)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.containerTabs.addTab(self.syncDialog, "")
        self.cropDialog = QtGui.QWidget()
        self.cropDialog.setObjectName("cropDialog")
        self.containerTabs.addTab(self.cropDialog, "")
        self.horizontalLayout_5.addWidget(self.containerTabs)
        self.widgetStack.addWidget(self.editContainer)
        self.editAudio = QtGui.QWidget()
        self.editAudio.setObjectName("editAudio")
        self.playSampleButton = QtGui.QPushButton(self.editAudio)
        self.playSampleButton.setGeometry(QtCore.QRect(160, 10, 93, 27))
        self.playSampleButton.setObjectName("playSampleButton")
        self.changeAudioButton = QtGui.QPushButton(self.editAudio)
        self.changeAudioButton.setGeometry(QtCore.QRect(160, 50, 91, 27))
        self.changeAudioButton.setObjectName("changeAudioButton")
        self.verifyAudioButton = QtGui.QPushButton(self.editAudio)
        self.verifyAudioButton.setGeometry(QtCore.QRect(160, 120, 101, 27))
        self.verifyAudioButton.setObjectName("verifyAudioButton")
        self.changeAudioEdit = QtGui.QLineEdit(self.editAudio)
        self.changeAudioEdit.setGeometry(QtCore.QRect(260, 50, 113, 27))
        self.changeAudioEdit.setObjectName("changeAudioEdit")
        self.layoutWidget = QtGui.QWidget(self.editAudio)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 104, 75))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.audioLabel = QtGui.QLabel(self.layoutWidget)
        self.audioLabel.setObjectName("audioLabel")
        self.verticalLayout_10.addWidget(self.audioLabel)
        self.audioSyncLabel = QtGui.QLabel(self.layoutWidget)
        self.audioSyncLabel.setObjectName("audioSyncLabel")
        self.verticalLayout_10.addWidget(self.audioSyncLabel)
        self.removeAudio = QtGui.QPushButton(self.layoutWidget)
        self.removeAudio.setObjectName("removeAudio")
        self.verticalLayout_10.addWidget(self.removeAudio)
        self.forceExactTime = QtGui.QCheckBox(self.editAudio)
        self.forceExactTime.setGeometry(QtCore.QRect(160, 80, 211, 22))
        self.forceExactTime.setObjectName("forceExactTime")
        self.widgetStack.addWidget(self.editAudio)
        self.editFile = QtGui.QWidget()
        self.editFile.setObjectName("editFile")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.editFile)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.filenameLabel = QtGui.QLabel(self.editFile)
        self.filenameLabel.setObjectName("filenameLabel")
        self.verticalLayout_5.addWidget(self.filenameLabel)
        self.label_2 = QtGui.QLabel(self.editFile)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.moveUp = QtGui.QPushButton(self.editFile)
        self.moveUp.setObjectName("moveUp")
        self.verticalLayout_6.addWidget(self.moveUp)
        self.moveDown = QtGui.QPushButton(self.editFile)
        self.moveDown.setObjectName("moveDown")
        self.verticalLayout_6.addWidget(self.moveDown)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.removeFile = QtGui.QPushButton(self.editFile)
        self.removeFile.setObjectName("removeFile")
        self.verticalLayout_6.addWidget(self.removeFile)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.widgetStack.addWidget(self.editFile)
        self.verticalLayout_2.addWidget(self.widgetStack)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prepareButton = QtGui.QPushButton(self.centralwidget)
        self.prepareButton.setObjectName("prepareButton")
        self.horizontalLayout_2.addWidget(self.prepareButton)
        self.syncButton = QtGui.QPushButton(self.centralwidget)
        self.syncButton.setObjectName("syncButton")
        self.horizontalLayout_2.addWidget(self.syncButton)
        self.mergeButton = QtGui.QPushButton(self.centralwidget)
        self.mergeButton.setObjectName("mergeButton")
        self.horizontalLayout_2.addWidget(self.mergeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.widgetStack.setCurrentIndex(1)
        self.containerTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Layout:", None, QtGui.QApplication.UnicodeUTF8))
        self.setDefaultLayout.setText(QtGui.QApplication.translate("MainWindow", "set default", None, QtGui.QApplication.UnicodeUTF8))
        self.createSetButton.setText(QtGui.QApplication.translate("MainWindow", "Create Set", None, QtGui.QApplication.UnicodeUTF8))
        self.setLayoutButton.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.removeSetButton.setText(QtGui.QApplication.translate("MainWindow", "remove Set", None, QtGui.QApplication.UnicodeUTF8))
        self.addAudioButton.setText(QtGui.QApplication.translate("MainWindow", "add Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.containerName.setText(QtGui.QApplication.translate("MainWindow", "Name: ContainerName", None, QtGui.QApplication.UnicodeUTF8))
        self.containerStatus.setText(QtGui.QApplication.translate("MainWindow", "Status: ContainerStatus", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Use Orignal Files", None, QtGui.QApplication.UnicodeUTF8))
        self.addFileButton.setText(QtGui.QApplication.translate("MainWindow", "Add File", None, QtGui.QApplication.UnicodeUTF8))
        self.containerTabs.setTabText(self.containerTabs.indexOf(self.fileDialog), QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.changeSyncButton.setText(QtGui.QApplication.translate("MainWindow", "change events", None, QtGui.QApplication.UnicodeUTF8))
        self.verifyButton.setText(QtGui.QApplication.translate("MainWindow", "verify events", None, QtGui.QApplication.UnicodeUTF8))
        self.event1pic.setText(QtGui.QApplication.translate("MainWindow", "e1pic", None, QtGui.QApplication.UnicodeUTF8))
        self.event1text.setText(QtGui.QApplication.translate("MainWindow", "e1text", None, QtGui.QApplication.UnicodeUTF8))
        self.event2pic.setText(QtGui.QApplication.translate("MainWindow", "e2pic", None, QtGui.QApplication.UnicodeUTF8))
        self.event2text.setText(QtGui.QApplication.translate("MainWindow", "e2text", None, QtGui.QApplication.UnicodeUTF8))
        self.containerTabs.setTabText(self.containerTabs.indexOf(self.syncDialog), QtGui.QApplication.translate("MainWindow", "Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.containerTabs.setTabText(self.containerTabs.indexOf(self.cropDialog), QtGui.QApplication.translate("MainWindow", "Cropping", None, QtGui.QApplication.UnicodeUTF8))
        self.playSampleButton.setText(QtGui.QApplication.translate("MainWindow", "play sample", None, QtGui.QApplication.UnicodeUTF8))
        self.changeAudioButton.setText(QtGui.QApplication.translate("MainWindow", "change sync", None, QtGui.QApplication.UnicodeUTF8))
        self.verifyAudioButton.setText(QtGui.QApplication.translate("MainWindow", "verify sync", None, QtGui.QApplication.UnicodeUTF8))
        self.audioLabel.setText(QtGui.QApplication.translate("MainWindow", "audioLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.audioSyncLabel.setText(QtGui.QApplication.translate("MainWindow", "audioSyncLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.removeAudio.setText(QtGui.QApplication.translate("MainWindow", "remove", None, QtGui.QApplication.UnicodeUTF8))
        self.forceExactTime.setText(QtGui.QApplication.translate("MainWindow", "force exact time", None, QtGui.QApplication.UnicodeUTF8))
        self.filenameLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUp.setText(QtGui.QApplication.translate("MainWindow", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDown.setText(QtGui.QApplication.translate("MainWindow", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.removeFile.setText(QtGui.QApplication.translate("MainWindow", "Remove File", None, QtGui.QApplication.UnicodeUTF8))
        self.prepareButton.setText(QtGui.QApplication.translate("MainWindow", "Prepare Container", None, QtGui.QApplication.UnicodeUTF8))
        self.syncButton.setText(QtGui.QApplication.translate("MainWindow", "Detect Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.mergeButton.setText(QtGui.QApplication.translate("MainWindow", "Create Views", None, QtGui.QApplication.UnicodeUTF8))

from layout_preview import LayoutPreview
