# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoWidget.ui'
#
# Created: Fri Mar  2 14:33:51 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_videoWidget(object):
    def setupUi(self, videoWidget):
        videoWidget.setObjectName("videoWidget")
        videoWidget.resize(446, 488)
        videoWidget.setStyleSheet("None")
        self.verticalLayout = QtGui.QVBoxLayout(videoWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoLayer = CVVideoWidget(videoWidget)
        self.videoLayer.setObjectName("videoLayer")
        self.verticalLayout.addWidget(self.videoLayer)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previousButton = QtGui.QPushButton(videoWidget)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.nextButton = QtGui.QPushButton(videoWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.gotoButton = QtGui.QPushButton(videoWidget)
        self.gotoButton.setObjectName("gotoButton")
        self.horizontalLayout.addWidget(self.gotoButton)
        self.frameInput = QtGui.QLineEdit(videoWidget)
        self.frameInput.setObjectName("frameInput")
        self.horizontalLayout.addWidget(self.frameInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setE1Button = QtGui.QPushButton(videoWidget)
        self.setE1Button.setObjectName("setE1Button")
        self.horizontalLayout_2.addWidget(self.setE1Button)
        self.gotoE1Button = QtGui.QPushButton(videoWidget)
        self.gotoE1Button.setObjectName("gotoE1Button")
        self.horizontalLayout_2.addWidget(self.gotoE1Button)
        self.setE2Button = QtGui.QPushButton(videoWidget)
        self.setE2Button.setObjectName("setE2Button")
        self.horizontalLayout_2.addWidget(self.setE2Button)
        self.gotoE2Button = QtGui.QPushButton(videoWidget)
        self.gotoE2Button.setObjectName("gotoE2Button")
        self.horizontalLayout_2.addWidget(self.gotoE2Button)
        self.currentFrameLabel = QtGui.QLabel(videoWidget)
        self.currentFrameLabel.setObjectName("currentFrameLabel")
        self.horizontalLayout_2.addWidget(self.currentFrameLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.event1Label = QtGui.QLabel(videoWidget)
        self.event1Label.setObjectName("event1Label")
        self.horizontalLayout_3.addWidget(self.event1Label)
        self.event2Label = QtGui.QLabel(videoWidget)
        self.event2Label.setObjectName("event2Label")
        self.horizontalLayout_3.addWidget(self.event2Label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.e1List = QtGui.QListWidget(videoWidget)
        self.e1List.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.e1List.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.e1List.setIconSize(QtCore.QSize(300, 200))
        self.e1List.setFlow(QtGui.QListView.LeftToRight)
        self.e1List.setViewMode(QtGui.QListView.ListMode)
        self.e1List.setObjectName("e1List")
        self.horizontalLayout_4.addWidget(self.e1List)
        self.e2List = QtGui.QListWidget(videoWidget)
        self.e2List.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.e2List.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.e2List.setIconSize(QtCore.QSize(300, 200))
        self.e2List.setFlow(QtGui.QListView.LeftToRight)
        self.e2List.setViewMode(QtGui.QListView.ListMode)
        self.e2List.setObjectName("e2List")
        self.horizontalLayout_4.addWidget(self.e2List)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.acceptButton = QtGui.QPushButton(videoWidget)
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_5.addWidget(self.acceptButton)
        self.declineButton = QtGui.QPushButton(videoWidget)
        self.declineButton.setObjectName("declineButton")
        self.horizontalLayout_5.addWidget(self.declineButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(videoWidget)
        QtCore.QObject.connect(self.acceptButton, QtCore.SIGNAL("clicked()"), videoWidget.accept)
        QtCore.QObject.connect(self.declineButton, QtCore.SIGNAL("clicked()"), videoWidget.reject)
        QtCore.QMetaObject.connectSlotsByName(videoWidget)

    def retranslateUi(self, videoWidget):
        videoWidget.setWindowTitle(QtGui.QApplication.translate("videoWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.previousButton.setText(QtGui.QApplication.translate("videoWidget", "previous", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("videoWidget", "next", None, QtGui.QApplication.UnicodeUTF8))
        self.gotoButton.setText(QtGui.QApplication.translate("videoWidget", "goto", None, QtGui.QApplication.UnicodeUTF8))
        self.setE1Button.setText(QtGui.QApplication.translate("videoWidget", "set E1", None, QtGui.QApplication.UnicodeUTF8))
        self.gotoE1Button.setText(QtGui.QApplication.translate("videoWidget", "goto E1", None, QtGui.QApplication.UnicodeUTF8))
        self.setE2Button.setText(QtGui.QApplication.translate("videoWidget", "set E2", None, QtGui.QApplication.UnicodeUTF8))
        self.gotoE2Button.setText(QtGui.QApplication.translate("videoWidget", "goto E2", None, QtGui.QApplication.UnicodeUTF8))
        self.currentFrameLabel.setText(QtGui.QApplication.translate("videoWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.event1Label.setText(QtGui.QApplication.translate("videoWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.event2Label.setText(QtGui.QApplication.translate("videoWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.acceptButton.setText(QtGui.QApplication.translate("videoWidget", "accept", None, QtGui.QApplication.UnicodeUTF8))
        self.declineButton.setText(QtGui.QApplication.translate("videoWidget", "decline", None, QtGui.QApplication.UnicodeUTF8))

from qtpromotion import CVVideoWidget
