# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox coveralls

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

after_success:
    "coveralls"

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  user: stibbons
  distributions: sdist bdist_wheel
  password:
    secure: IHSLyza/BoER1mMVlmaNr4EGGv4d6n0TPKZTrMPi4KsW7FuFvEeiVqX5VFHi54L1EMX8fg0gb4to0LjMyo+wVPSLcDxq5me4MSwPYulgSigEPE9ixVI7R+q8GrkURiSdDeH6PV1kKH9iLDNH9fHunC2a+Nkk4vk6WcFPv1cXLOkX+S8GcHpaHd3NL2kykcotw1b7vUOE96i528IXDK9s4OL2+TPymGuphQysEx1Pop4LPrilk3CfGkZTmKwiF9QhBEfuqJu550SUEs30UMlSBmvC4qGZaeeVpwNSWVrz9lpw/VkR/G0hO0Jt4BY1vODsFpzOog/BrV/EIiMiNHtVU83SeJiQLnmNtoRgJ+HYms/vlst63m+XV/7KzcFNTlZu5aa9Icol3JQT3nZJkfGIWafojtYiIA1lLqYmxtNqLEp5gB+huio79KK9vAkPyr/O532EEMK5nJv06nwXuQCGUnC9XB0qPlzszIj3GVMGhLvMywTUTo+pykuPtqCcSsFkt5fs3JQYxn/wZU+fKnGgUivy/FusD9MPGDIU69wuEye59nUhVTT1092FOZf/uraH8w6n/oTnSjQ984U102nZq983O/bDaVs1DKYgrylyvJ6ERanUt8cZSBQ5ksEqbILE9rYJXVmosjkOjcpXrCEsXJ5UQ98JQ22Q7VWeBEbzqIw=
  on:
    all_branches: true
    repo: stibbons/txrwlock
    condition: $TRAVIS_TAG != ""
