
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6a5f334cad3bc72aa5cedce79bb8dc4b418e3f58",
 "version": "0.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
