language: python
sudo: true
python:
  - 2.7
  - 3.5
env:
  global:
   - PBR_VERSION="1.2.3"
  matrix:
   - DJANGO_REQUIREMENT="Django>=1.8,<1.9"
   - DJANGO_REQUIREMENT="Django>=1.9rc2"
   - DB=postgres
   - DB=sqlite
before_install:
  - sudo apt-get install build-essential libssl-dev libffi-dev python-dev -y
install:
  - pip install -q $DJANGO_REQUIREMENT flake8
  - pip install -r requirements/tests.txt
  - python setup.py -q install
  - if [[ $DB == postgres ]]; then pip install -q psycopg2; fi
before_script:
  - psql -c 'create database django_leonardo;' -U postgres
script:
  - cd tests
  - coverage run manage.py test testapp && flake8 ../app_loader
after_success:
  - coveralls
branches:
  only:
    - master
