
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.0b4'
version_full = '005f7b59459ed0e22d96017810cdf4ea1eec0a20'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

