
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.14.1'
version_full = 'cceb99ceab55608e8556a4961fb1b71024f04c13'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

