
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "72b8121763072bd5e6931058ab89fd6c14e84fb6",
 "version": "0.7.post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
