
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-10-05T07:28:37-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2813bdac578753f4ab5d129e2fc077300e5d0eb4",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
