language: python
sudo: false
python:
    - "2.7"
install:
    - python bootstrap.py
    - bin/buildout
script:
    - bin/alltests -v
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
