
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-10-07T11:00:35-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc8f19123986e003ab7bf566cc8c43b98eba8007",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
