
# This file is automatically generated from sisl setup.py
major   = 0
minor   = 7
micro   = 7
version = '.'.join(map(str,[0, 7, 7]))
release = True
# Git information
git_rev = '66ad03a58dd71c5225278c12c6ce0c3206745f66'
git_rev_short = git_rev[:7]

if not release:
    version = version + '-' + git_rev_short
