
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.1.3'
version_full = '5bb873d43ed18bbc1dea3f5914ed9c8763622a24'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

