
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0537774b7e1a85435fd1dc4acf1fcb61e80f21b8",
 "version": "1.0.0.post.dev279"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
