from setuptools import setup

setup(name='dedent',
      version='0.5',
      description='Write inline code as easily as it should be',
      url='http://github.com/ctismer/dedent',
      author='Christian Tismer',
      author_email='tismer@stackless.com',
      license='MIT',
      packages=['dedent'],
      classifiers=[
          "Development Status :: 5 - Production/Stable",
          "Intended Audience :: Developers",
          "License :: OSI Approved :: BSD License",
          "Operating System :: Unix",
          "Operating System :: POSIX",
          "Operating System :: Microsoft :: Windows",
          "Programming Language :: Python",
          "Programming Language :: Python :: 2.6",
          "Programming Language :: Python :: 2.7",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3.3",
          "Programming Language :: Python :: 3.4",
          "Programming Language :: Python :: 3.5",
          "Programming Language :: Python :: Implementation :: CPython",
          "Programming Language :: Python :: Implementation :: PyPy",
          "Topic :: Utilities",
      ],
      install_requires=[
      ],
      zip_safe=False)
