
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-10-07T06:41:07+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "695b7e7588efa5ab568d9ca20eef13c7c78bb920",
 "version": "1.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
