
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f2ecaaa2834a5177539c53b576bed7ea557b8838",
 "version": "1.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
