
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f84991e32f5f25cce002497d9c3d61b52a7214c3",
 "version": "2016.0907.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
