__version__ = "0.2"
__git_commiter_name__ = "Itai Shirav"
__git_commiter_email__ = "itais@infinidat.com"
__git_branch__ = '(HEAD detached at v0.2)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ec1b7734e381db41e885cf6df4764ecb555a609e'
__git_head_subject__ = 'Finished Release v0.2'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-10-05 16:49:37'
