
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(BuildFileAddress(FilesystemBuildFile(/Users/jdorlus/dev/GitHub/twitter_commons/src/python/twitter/common/log/BUILD), log))

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': 'twitter.common logging handlers.',
    'install_requires': [   'twitter.common.dirutil==0.3.9',
                            'twitter.common.options==0.3.9'],
    'license': 'Apache License, Version 2.0',
    'name': 'twitter.common.log',
    'namespace_packages': ['twitter', 'twitter.common'],
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': [   'twitter',
                    'twitter.common',
                    'twitter.common.log',
                    'twitter.common.log.formatters'],
    'url': 'https://github.com/twitter/commons',
    'version': '0.3.9',
    'zip_safe': True}
)
