
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "21f1be62a99e6fb6dd525cc536560dc4be02af27",
 "version": "0.1.8.post.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
