---
- name: Create infrastructure services directory
  file:
    path:  /home/{{ admin_user }}/services-infrastructure/
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"

# Create namespace
- name: Copy namespace.yaml
  template:
    src:   namespace.yaml.j2
    dest:  /home/{{ admin_user }}/services-infrastructure/namespace.yaml
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
  #delegate_to: "{{ groups['k8sdc-master'] | first }}"
  #run_once: yes

- name: Check if infrastructure services namespace already exists
  command: kubectl get namespace {{ infrastructure_namespace }}
  failed_when: false
  register: kubectl

- name: Create infrastructure services namespace if required
  command: kubectl create -f namespace.yaml
  args:
    chdir: /home/{{ admin_user }}/services-infrastructure/
  when: "'{{ infrastructure_namespace }}' not in kubectl.stdout"

# OpenDJ
- include: opendj.yml
  tags: opendj

# Romulus
- name: Create Romulus directory
  file:
    path:  /home/{{ admin_user }}/{{ infrastructure_namespace }}/romulus/
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
  tags: romulus

# Romulus Secret
- include: romulus_secret.yml
  tags: romulus

# Vulcand and Romulus - Internal
- include: vulcand_romulus.yml node="{{ groups['k8sdc-nodes'][0] }}" location=internal
  tags: 
    - romulus
    - vulcand_internal

# Vulcand and Romulus - External
- include: vulcand_romulus.yml node="{{ groups['k8sdc-nodes'][1] }}" location=external
  tags: 
    - romulus
    - vulcand_external
