---
- name: Copy Vulcand files
  template:
    src: vulcand/vulcand-pod.yaml.j2
    dest: /etc/kubernetes/manifest/vulcand-pod.yaml
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
  delegate_to: "{{ node }}"

- name: Copy Romulus files
  template:
    src: romulus/romulus-pod.yaml.j2
    dest: /home/{{ admin_user }}/{{ infrastructure_namespace }}/romulus/romulus-{{ location }}-pod.yaml
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"

# Pod
- name: Create Romulus Pod if it does not currently exist
  command: kubectl create -f romulus-{{ location }}-pod.yaml
  args:
    chdir: /home/{{ admin_user }}/services-infrastructure/romulus
  failed_when: false
  register: kubectl
  changed_when: "'already exists' not in kubectl.stderr"

- name: Delete Romulus Pod if it already exists
  command: kubectl delete po romulus-{{ location }} --namespace={{ infrastructure_namespace }}
  args:
    chdir: /home/{{ admin_user }}/services-infrastructure/romulus
  when: not kubectl.changed

- name: Re-create Romulus Pod
  command: kubectl create -f romulus-{{ location }}-pod.yaml
  args:
    chdir: /home/{{ admin_user }}/services-infrastructure/romulus
  when: not kubectl.changed
