from telethon.tl.mtproto_request import MTProtoRequest


class FileGif(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    storage.fileGif#cae1aadf  = storage.FileType"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xcae1aadf

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'storage.fileGif#cae1aadf  = storage.FileType'

    def __str__(self):
        return '(storage.fileGif (ID: 0xcae1aadf) = ())'.format()
