from telethon.tl.mtproto_request import MTProtoRequest


class FilePng(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    storage.filePng#0a4f63c0  = storage.FileType"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xa4f63c0

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'storage.filePng#0a4f63c0  = storage.FileType'

    def __str__(self):
        return '(storage.filePng (ID: 0xa4f63c0) = ())'.format()
