sudo: true
dist: trusty

language: python

python:
  - "2.7_with_system_site_packages"

cache:
  - pip
  - apt

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-gi gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"

deploy:
  provider: pypi
  user: palfrey
  password:
    secure: K3Mo/HqRK2ZtYfMoF1yQzHAtN1ckSqLsFtwRQ2hjdjabFT8/hIpCs1kHR6uyEGAdH6jGDO9XNu6l7021ZbV7dZfeegx+eDzuiyWEKktYJEAvs0eb7GB6mOtNrOVcWXLJRL0ASWMbAh1zPg/TjaEw+ETZp/KBu6i8QPZ0Gf/QiiWebcX7JKgAdhJusYHsz+9DhDuJ2iE4Ped+/eFpeY5Zgv8UmnYYOY+XUF0/UgbgnY+qWgUK8dlNCJzQjvCmJgbsYZX5p20Uj4wTSKGnnVOjkTGwWJgQ1ZS8OR6S2qreXhgrtPowgfe7wfy+LmtRGn1p2OUrBnOOJZOvfAmyGy9TNAiUeKqDefQQlMIZxl7W7zZGbU4eZcZnXrTqWPj5jSJfyMOnjbn23fQYZ8PFgCEiXWWhSLJml77TO83S4GcCbwvYwu+Em8SXNsx8H7Q6HZQC8CHaC27vlISVta7aiTTrqVAY5PZO36Nv+dWBWbM9ZFrgs4LPn0HikAvRj8DXHlKv9azgO9cw/pSCNtMwILUuxG/SIz4+HjDgkz0aOgcehu2TW5SQYE0Q9e6k4TCrubWvZeQRt+09Ob0s2dikRmrPxOxxaJKKJnKMdV7iS9nUECwKpHjybi2S9m9FPl9M7hnSWFFdU1pad+ZUGVEOUbfIiRDpXBUAUrxp+Ve4WfOGNtg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: palfrey/mopidy-tachikoma
