
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4c00b05a7124346e25c8989337361240f9a62faa",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
