language: python
sudo: false
python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
env:
   - DJANGO_VERSION=1.8 TESTDB=sqlite
   - DJANGO_VERSION=1.8 TESTDB=postgres
   - DJANGO_VERSION=1.9 TESTDB=sqlite
   - DJANGO_VERSION=1.9 TESTDB=postgres
matrix:
   exclude:
      # Django 1.9 doesn't support 3.3
      - python: "3.3"
        env: DJANGO_VERSION=1.9 TESTDB=sqlite
      - python: "3.3"
        env: DJANGO_VERSION=1.9 TESTDB=postgres
services:
   - postgresql
before_install:
   - if [ "$TESTDB" = "postgres" ]; then pip install -q psycopg2 ; fi
# command to install dependencies,
install:
   # Install the right version of Django first
   - pip install 'Django~='"$DJANGO_VERSION".0
   - pip install -r requirements.txt -r requirements-dev.txt
# command to run tests
script: NOSE_WITH_COVERAGE=1 python manage.py test
