
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "55546a7d238e96cd0ffea86f3bb80d03e273e152",
 "version": "0.1.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
