
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-10-04T15:26:47+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "192449309da896a9fc005f90ce8ec2d93c63e6f2",
 "version": "1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
