from telethon.tl.mtproto_request import MTProtoRequest


class FileUnknown(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    storage.fileUnknown#aa963b05  = storage.FileType"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xaa963b05

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'storage.fileUnknown#aa963b05  = storage.FileType'

    def __str__(self):
        return '(storage.fileUnknown (ID: 0xaa963b05) = ())'.format()
