from telethon.tl.mtproto_request import MTProtoRequest


class FileWebp(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    storage.fileWebp#1081464c  = storage.FileType"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x1081464c

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'storage.fileWebp#1081464c  = storage.FileType'

    def __str__(self):
        return '(storage.fileWebp (ID: 0x1081464c) = ())'.format()
