---

- name: Read the CA certificate
  slurp:
    src: "/etc/kubernetes/certs/ca.crt"
  register: ca_cert

- name: Read kubecfg.key
  slurp:
    src: "/etc/kubernetes/certs/kubecfg.key"
  register: kubecfg_key

- name: Read kubecfg.crt
  slurp:
    src: "/etc/kubernetes/certs/kubecfg.crt"
  register: kubecfg_crt

- name: Copy Romulus secret file
  template:
    src: romulus/romulus-secret.yaml.j2
    dest: /home/{{ admin_user }}/{{ infrastructure_namespace }}/romulus/romulus-secret.yaml
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"

- name: Create Romulus secret if it does not currently exist
  command: kubectl create -f romulus-secret.yaml
  args:
    chdir: /home/{{ admin_user }}/services-infrastructure/romulus
  failed_when: false
  register: kubectl
  changed_when: "'already exists' not in kubectl.stderr"

- name: Delete Romulus secret if it already exists
  command: kubectl delete secret romulus-secret --namespace={{ infrastructure_namespace }}
  args:
    chdir: /home/{{ admin_user }}/services-infrastructure/romulus
  when: not kubectl.changed

- name: Re-create Romulus secret
  command: kubectl create -f romulus-secret.yaml
  args:
    chdir: /home/{{ admin_user }}/services-infrastructure/romulus
  when: not kubectl.changed
