from telethon.tl.mtproto_request import MTProtoRequest


class GetWallPapersRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    account.getWallPapers#c04cfac2  = Vector<WallPaper>"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0xc04cfac2

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'account.getWallPapers#c04cfac2  = Vector<WallPaper>'

    def __str__(self):
        return '(account.getWallPapers (ID: 0xc04cfac2) = ())'.format()
