from telethon.tl.mtproto_request import MTProtoRequest


class GetPasswordRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    account.getPassword#548a30f5  = account.Password"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x548a30f5

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'account.getPassword#548a30f5  = account.Password'

    def __str__(self):
        return '(account.getPassword (ID: 0x548a30f5) = ())'.format()
