from telethon.tl.mtproto_request import MTProtoRequest


class ResetNotifySettingsRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    account.resetNotifySettings#db7e1747  = Bool"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0xdb7e1747

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'account.resetNotifySettings#db7e1747  = Bool'

    def __str__(self):
        return '(account.resetNotifySettings (ID: 0xdb7e1747) = ())'.format()
