
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8f195c6b730803b1908b3bac9e8e3de822f7a618",
 "version": "1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
