
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4ea99a7dd8c35672320427879fa98d04bfd7df06",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
