from telethon.tl.mtproto_request import MTProtoRequest


class GetContactsRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    contacts.getContacts#22c6aa08 hash:string = contacts.Contacts"""

    def __init__(self, hash):
        """
        :param hash: Telegram type: «string».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x22c6aa08

        self.hash = hash

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_string(self.hash)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'contacts.getContacts#22c6aa08 hash:string = contacts.Contacts'

    def __str__(self):
        return '(contacts.getContacts (ID: 0x22c6aa08) = (hash={}))'.format(str(self.hash))
