heat_template_version: 2016-04-08

description: >
  OpenStack Neutron Metadata service with Pacemaker configured with Puppet.

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NeutronMetadataBase:
    type: ../neutron-metadata.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Neutron Metadata role.
    value:
      service_name: neutron_metadata
      config_settings:
        map_merge:
          - get_attr: [NeutronMetadataBase, role_data, config_settings]
          - tripleo::profile::pacemaker::neutron::enable_metadata: True
      step_config: |
        include ::tripleo::profile::pacemaker::neutron::metadata
