heat_template_version: 2016-04-08

description: >
  OpenStack Sahara Engine service with Pacemaker configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  SaharaEngineBase:
    type: ../sahara-engine.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Sahara Engine role.
    value:
      service_name: sahara_engine
      config_settings:
        map_merge:
          - get_attr: [SaharaEngineBase, role_data, config_settings]
          - sahara::service::engine::manage_service: false
            sahara::service::engine::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::sahara::engine
