
# This file is automatically generated from sisl setup.py
major   = 0
minor   = 7
micro   = 8
version = '.'.join(map(str,[0, 7, 8]))
release = True
# Git information
git_rev = '8f2a1a0338487dbbbc1db8f92e534f0efbf15ffa'
git_rev_short = git_rev[:7]

if not release:
    version = version + '-' + git_rev_short
