image: mgoral/super-ci-runner:latest

stages:
    - test
    - deploy

before_script:
    - pip3 install tox

test:
    stage: test
    script:
        - tox -e py33
        - tox -e py34
        - tox -e py35

test-pylint:
    stage: test
    script:
        - tox -e pylint

test-flake8:
    stage: test
    script:
        - tox -e flake8

dist:
    stage: deploy
    before_script:
        - pip3 install -rreqs/requirements-deploy.txt
    only:
        - tags
        - triggers
    script:
        - python3 setup.py sdist bdist_wheel
        - twine upload dist/* -u "$PYPI_USER" -p "$PYPI_PASS"
    artifacts:
        name: "${CI_PROJECT_NAME}-{$CI_BUILD_REF_NAME}"
        paths:
            - dist/
