from telethon.tl.mtproto_request import MTProtoRequest


class EditAboutRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    channels.editAbout#13e27f1e channel:InputChannel about:string = Bool"""

    def __init__(self, channel, about):
        """
        :param channel: Telegram type: «InputChannel».
        :param about: Telegram type: «string».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x13e27f1e

        self.channel = channel
        self.about = about

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        self.channel.on_send(writer)
        writer.tgwrite_string(self.about)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'channels.editAbout#13e27f1e channel:InputChannel about:string = Bool'

    def __str__(self):
        return '(channels.editAbout (ID: 0x13e27f1e) = (channel={}, about={}))'.format(str(self.channel), str(self.about))
