from telethon.tl.mtproto_request import MTProtoRequest


class EditTitleRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    channels.editTitle#566decd0 channel:InputChannel title:string = Updates"""

    def __init__(self, channel, title):
        """
        :param channel: Telegram type: «InputChannel».
        :param title: Telegram type: «string».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x566decd0

        self.channel = channel
        self.title = title

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        self.channel.on_send(writer)
        writer.tgwrite_string(self.title)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'channels.editTitle#566decd0 channel:InputChannel title:string = Updates'

    def __str__(self):
        return '(channels.editTitle (ID: 0x566decd0) = (channel={}, title={}))'.format(str(self.channel), str(self.title))
