from telethon.tl.mtproto_request import MTProtoRequest


class ExportInviteRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    channels.exportInvite#c7560885 channel:InputChannel = ExportedChatInvite"""

    def __init__(self, channel):
        """
        :param channel: Telegram type: «InputChannel».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0xc7560885

        self.channel = channel

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        self.channel.on_send(writer)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'channels.exportInvite#c7560885 channel:InputChannel = ExportedChatInvite'

    def __str__(self):
        return '(channels.exportInvite (ID: 0xc7560885) = (channel={}))'.format(str(self.channel))
