from telethon.tl.mtproto_request import MTProtoRequest


class JoinChannelRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    channels.joinChannel#24b524c5 channel:InputChannel = Updates"""

    def __init__(self, channel):
        """
        :param channel: Telegram type: «InputChannel».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x24b524c5

        self.channel = channel

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        self.channel.on_send(writer)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'channels.joinChannel#24b524c5 channel:InputChannel = Updates'

    def __str__(self):
        return '(channels.joinChannel (ID: 0x24b524c5) = (channel={}))'.format(str(self.channel))
