---
- include: do_reconfigure.yml
  serial: "30%"
  when: inventory_hostname in groups['barbican-api']
        or inventory_hostname in groups['barbican-keystone-listener']
        or inventory_hostname in groups['barbican-worker']
