
# common_DiceParser_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'C4867F784517EC39E2C1C5DEC136B926'
    
_lr_action_items = {'$end':([1,2,3,7,8,9,],[-5,0,-1,-2,-3,-4,]),'DIGIT':([0,4,5,6,],[1,7,1,1,]),'DSEPARATOR':([1,],[4,]),'ADD':([1,3,7,8,9,],[-5,5,-2,-3,-4,]),'SUB':([1,3,7,8,9,],[-5,6,-2,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,6,],[3,8,9,]),'statement':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','dice.py',60),
  ('expression -> DIGIT DSEPARATOR DIGIT','expression',3,'p_expression_dice','dice.py',65),
  ('expression -> expression ADD expression','expression',3,'p_expression_binop','dice.py',71),
  ('expression -> expression SUB expression','expression',3,'p_expression_binop','dice.py',72),
  ('expression -> DIGIT','expression',1,'p_expression_digit','dice.py',82),
]
