
/* #########################################################################
 * [2016-10-09 09:07:51.566000] THIS FILE IS AUTOGENERATED - DO NOT EDIT!
 * ######################################################################### */

#ifndef ___DROPBOT_DX___
#define ___DROPBOT_DX___

#include "DropbotDx/Properties.h"
#include "DropbotDx/CommandProcessor.h"

#endif  // #ifndef ___DROPBOT_DX___

