## A Heat environment file which can be used to set up monitoring
## and logging agents

resource_registry:
  OS::TripleO::Services::SensuClient: ../puppet/services/monitoring/sensu-client.yaml

parameter_defaults:
  #### Sensu settings ####
  ##MonitoringRabbitHost: 10.10.10.10
  ##MonitoringRabbitPort: 5672
  ##MonitoringRabbitUserName: sensu
  ##MonitoringRabbitPassword: sensu
  ##MonitoringRabbitUseSSL: false
  ##MonitoringRabbitVhost: "/sensu"
  ##SensuClientCustomConfig:
  ##  - api:
  ##    - warning: 10
  ##      critical: 20
  ##    openstack:
  ##    - username: admin
  ##      password: changeme
  ##      project_name: admin
  ##      auth_url: http://controller:5000/v2.0
  ##      region_name: RegionOne

  #### EFK settings ####
  ## TBD

  #### Grafana/Graphite settings ####
  ## TBD
