# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_g11n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dts_insert', models.DateTimeField(auto_now_add=True)),
                ('dts_update', models.DateTimeField(blank=True, null=True)),
                ('dts_delete', models.DateTimeField(blank=True, null=True)),
                ('numeric', models.CharField(max_length=3, unique=True)),
                ('english', models.CharField(max_length=64)),
                ('obsolete', models.BooleanField(default=False)),
                ('unsd_m49', models.BooleanField(default=False)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_g11n.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dts_insert', models.DateTimeField(auto_now_add=True)),
                ('dts_update', models.DateTimeField(blank=True, null=True)),
                ('dts_delete', models.DateTimeField(blank=True, null=True)),
                ('lower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_region_is_lower', to='django_g11n.Region')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_region_is_upper', to='django_g11n.Region')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='regionchain',
            unique_together=set([('upper', 'lower')]),
        ),
    ]
