
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(BuildFileAddress(FilesystemBuildFile(/Users/jdorlus/dev/GitHub/twitter_commons/src/python/twitter/common/rpc/BUILD), rpc-packaged))

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': 'twitter.common thrift helpers including finagle and ssl transports.',
    'extras_require': {   'sasl': ['kerberos==1.1.1', 'pure-sasl==0.1.4']},
    'install_requires': [   'thrift',
                            'twitter.common.lang==0.3.9',
                            'twitter.common.finagle-thrift==0.3.9'],
    'license': 'Apache License, Version 2.0',
    'name': 'twitter.common.rpc',
    'namespace_packages': ['twitter', 'twitter.common'],
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': [   'twitter',
                    'twitter.common',
                    'twitter.common.rpc',
                    'twitter.common.rpc.finagle',
                    'twitter.common.rpc.sasl',
                    'twitter.common.rpc.transports'],
    'url': 'https://github.com/twitter/commons',
    'version': '0.3.9',
    'zip_safe': True}
)
