from telethon.tl.mtproto_request import MTProtoRequest


class FeaturedStickersNotModified(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messages.featuredStickersNotModified#04ede3cf  = messages.FeaturedStickers"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x4ede3cf

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'messages.featuredStickersNotModified#04ede3cf  = messages.FeaturedStickers'

    def __str__(self):
        return '(messages.featuredStickersNotModified (ID: 0x4ede3cf) = ())'.format()
