from telethon.tl.mtproto_request import MTProtoRequest


class SentEncryptedMessage(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messages.sentEncryptedMessage#560f8935 date:date = messages.SentEncryptedMessage"""

    def __init__(self, date):
        """
        :param date: Telegram type: «date».
        """
        super().__init__()
        self.constructor_id = 0x560f8935

        self.date = date

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_date(self.date)

    def on_response(self, reader):
        self.date = reader.tgread_date()

    def __repr__(self):
        return 'messages.sentEncryptedMessage#560f8935 date:date = messages.SentEncryptedMessage'

    def __str__(self):
        return '(messages.sentEncryptedMessage (ID: 0x560f8935) = (date={}))'.format(str(self.date))
