from telethon.tl.mtproto_request import MTProtoRequest


class StickersNotModified(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messages.stickersNotModified#f1749a22  = messages.Stickers"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xf1749a22

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'messages.stickersNotModified#f1749a22  = messages.Stickers'

    def __str__(self):
        return '(messages.stickersNotModified (ID: 0xf1749a22) = ())'.format()
