
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d8bdf7e0d293c31097eb942c2467252f6e591e2a",
 "version": "0.0.0a14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
