cache: apt
sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - pip install biom-format

script:
  - python -m unittest discover -s test/ -vf

# command for email notifications, set to no notifications via email
notifications:
    email: false