
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d7b342347aa752917f0e7cc38a33f61ff0b3f208",
 "version": "0.1.8.post.dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
