from telethon.tl.mtproto_request import MTProtoRequest


class ContactLinkNone(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    contactLinkNone#feedd3ad  = ContactLink"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xfeedd3ad

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'contactLinkNone#feedd3ad  = ContactLink'

    def __str__(self):
        return '(contactLinkNone (ID: 0xfeedd3ad) = ())'.format()
