from telethon.tl.mtproto_request import MTProtoRequest


class InputMediaEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputMediaEmpty#9664f57f  = InputMedia"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x9664f57f

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputMediaEmpty#9664f57f  = InputMedia'

    def __str__(self):
        return '(inputMediaEmpty (ID: 0x9664f57f) = ())'.format()
