from telethon.tl.mtproto_request import MTProtoRequest


class InputNotifyUsers(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputNotifyUsers#193b4417  = InputNotifyPeer"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x193b4417

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputNotifyUsers#193b4417  = InputNotifyPeer'

    def __str__(self):
        return '(inputNotifyUsers (ID: 0x193b4417) = ())'.format()
