from telethon.tl.mtproto_request import MTProtoRequest


class InputNotifyAll(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputNotifyAll#a429b886  = InputNotifyPeer"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xa429b886

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputNotifyAll#a429b886  = InputNotifyPeer'

    def __str__(self):
        return '(inputNotifyAll (ID: 0xa429b886) = ())'.format()
