from telethon.tl.mtproto_request import MTProtoRequest


class InputChannelEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputChannelEmpty#ee8c1e86  = InputChannel"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xee8c1e86

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputChannelEmpty#ee8c1e86  = InputChannel'

    def __str__(self):
        return '(inputChannelEmpty (ID: 0xee8c1e86) = ())'.format()
