from telethon.tl.mtproto_request import MTProtoRequest


class InputEncryptedFileEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputEncryptedFileEmpty#1837c364  = InputEncryptedFile"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x1837c364

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'inputEncryptedFileEmpty#1837c364  = InputEncryptedFile'

    def __str__(self):
        return '(inputEncryptedFileEmpty (ID: 0x1837c364) = ())'.format()
