from telethon.tl.mtproto_request import MTProtoRequest


class InputNotifyPeer(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    inputNotifyPeer#b8bc5b0c peer:InputPeer = InputNotifyPeer"""

    def __init__(self, peer):
        """
        :param peer: Telegram type: «InputPeer».
        """
        super().__init__()
        self.constructor_id = 0xb8bc5b0c

        self.peer = peer

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        self.peer.on_send(writer)

    def on_response(self, reader):
        self.peer = reader.tgread_object()

    def __repr__(self):
        return 'inputNotifyPeer#b8bc5b0c peer:InputPeer = InputNotifyPeer'

    def __str__(self):
        return '(inputNotifyPeer (ID: 0xb8bc5b0c) = (peer={}))'.format(str(self.peer))
