from telethon.tl.mtproto_request import MTProtoRequest


class KeyboardButtonRequestGeoLocation(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    keyboardButtonRequestGeoLocation#fc796b3f text:string = KeyboardButton"""

    def __init__(self, text):
        """
        :param text: Telegram type: «string».
        """
        super().__init__()
        self.constructor_id = 0xfc796b3f

        self.text = text

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_string(self.text)

    def on_response(self, reader):
        self.text = reader.tgread_string()

    def __repr__(self):
        return 'keyboardButtonRequestGeoLocation#fc796b3f text:string = KeyboardButton'

    def __str__(self):
        return '(keyboardButtonRequestGeoLocation (ID: 0xfc796b3f) = (text={}))'.format(str(self.text))
