from telethon.tl.mtproto_request import MTProtoRequest


class MessageActionChatEditPhoto(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messageActionChatEditPhoto#7fcb13a8 photo:Photo = MessageAction"""

    def __init__(self, photo):
        """
        :param photo: Telegram type: «Photo».
        """
        super().__init__()
        self.constructor_id = 0x7fcb13a8

        self.photo = photo

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        self.photo.on_send(writer)

    def on_response(self, reader):
        self.photo = reader.tgread_object()

    def __repr__(self):
        return 'messageActionChatEditPhoto#7fcb13a8 photo:Photo = MessageAction'

    def __str__(self):
        return '(messageActionChatEditPhoto (ID: 0x7fcb13a8) = (photo={}))'.format(str(self.photo))
