from telethon.tl.mtproto_request import MTProtoRequest


class PeerNotifyEventsAll(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    peerNotifyEventsAll#6d1ded88  = PeerNotifyEvents"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x6d1ded88

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'peerNotifyEventsAll#6d1ded88  = PeerNotifyEvents'

    def __str__(self):
        return '(peerNotifyEventsAll (ID: 0x6d1ded88) = ())'.format()
