from telethon.tl.mtproto_request import MTProtoRequest


class PeerNotifySettingsEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    peerNotifySettingsEmpty#70a68512  = PeerNotifySettings"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x70a68512

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'peerNotifySettingsEmpty#70a68512  = PeerNotifySettings'

    def __str__(self):
        return '(peerNotifySettingsEmpty (ID: 0x70a68512) = ())'.format()
