from telethon.tl.mtproto_request import MTProtoRequest


class PhotoEmpty(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    photoEmpty#2331b22d id:long = Photo"""

    def __init__(self, id):
        """
        :param id: Telegram type: «long».
        """
        super().__init__()
        self.constructor_id = 0x2331b22d

        self.id = id

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.write_long(self.id)

    def on_response(self, reader):
        self.id = reader.read_long()

    def __repr__(self):
        return 'photoEmpty#2331b22d id:long = Photo'

    def __str__(self):
        return '(photoEmpty (ID: 0x2331b22d) = (id={}))'.format(str(self.id))
