from telethon.tl.mtproto_request import MTProtoRequest


class PrivacyKeyStatusTimestamp(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    privacyKeyStatusTimestamp#bc2eab30  = PrivacyKey"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xbc2eab30

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'privacyKeyStatusTimestamp#bc2eab30  = PrivacyKey'

    def __str__(self):
        return '(privacyKeyStatusTimestamp (ID: 0xbc2eab30) = ())'.format()
