from telethon.tl.mtproto_request import MTProtoRequest


class PrivacyValueAllowContacts(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    privacyValueAllowContacts#fffe1bac  = PrivacyRule"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xfffe1bac

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'privacyValueAllowContacts#fffe1bac  = PrivacyRule'

    def __str__(self):
        return '(privacyValueAllowContacts (ID: 0xfffe1bac) = ())'.format()
