from telethon.tl.mtproto_request import MTProtoRequest


class RpcAnswerUnknown(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    rpc_answer_unknown#5e2ad36e  = RpcDropAnswer"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x5e2ad36e

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'rpc_answer_unknown#5e2ad36e  = RpcDropAnswer'

    def __str__(self):
        return '(rpc_answer_unknown (ID: 0x5e2ad36e) = ())'.format()
