from telethon.tl.mtproto_request import MTProtoRequest


class SendMessageUploadDocumentAction(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    sendMessageUploadDocumentAction#aa0cd9e4 progress:int = SendMessageAction"""

    def __init__(self, progress):
        """
        :param progress: Telegram type: «int».
        """
        super().__init__()
        self.constructor_id = 0xaa0cd9e4

        self.progress = progress

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.write_int(self.progress)

    def on_response(self, reader):
        self.progress = reader.read_int()

    def __repr__(self):
        return 'sendMessageUploadDocumentAction#aa0cd9e4 progress:int = SendMessageAction'

    def __str__(self):
        return '(sendMessageUploadDocumentAction (ID: 0xaa0cd9e4) = (progress={}))'.format(str(self.progress))
