from telethon.tl.mtproto_request import MTProtoRequest


class SendMessageRecordAudioAction(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    sendMessageRecordAudioAction#d52f73f7  = SendMessageAction"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xd52f73f7

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'sendMessageRecordAudioAction#d52f73f7  = SendMessageAction'

    def __str__(self):
        return '(sendMessageRecordAudioAction (ID: 0xd52f73f7) = ())'.format()
