from telethon.tl.mtproto_request import MTProtoRequest


class SendMessageGeoLocationAction(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    sendMessageGeoLocationAction#176f8ba1  = SendMessageAction"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x176f8ba1

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'sendMessageGeoLocationAction#176f8ba1  = SendMessageAction'

    def __str__(self):
        return '(sendMessageGeoLocationAction (ID: 0x176f8ba1) = ())'.format()
