from telethon.tl.mtproto_request import MTProtoRequest


class TopPeerCategoryGroups(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    topPeerCategoryGroups#bd17a14a  = TopPeerCategory"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0xbd17a14a

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'topPeerCategoryGroups#bd17a14a  = TopPeerCategory'

    def __str__(self):
        return '(topPeerCategoryGroups (ID: 0xbd17a14a) = ())'.format()
