from telethon.tl.mtproto_request import MTProtoRequest


class UpdatePtsChanged(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    updatePtsChanged#3354678f  = Update"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x3354678f

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'updatePtsChanged#3354678f  = Update'

    def __str__(self):
        return '(updatePtsChanged (ID: 0x3354678f) = ())'.format()
