from telethon.tl.mtproto_request import MTProtoRequest


class UpdateInlineBotCallbackQuery(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    updateInlineBotCallbackQuery#2cbd95af query_id:long user_id:int msg_id:InputBotInlineMessageID data:bytes = Update"""

    def __init__(self, query_id, user_id, msg_id, data):
        """
        :param query_id: Telegram type: «long».
        :param user_id: Telegram type: «int».
        :param msg_id: Telegram type: «InputBotInlineMessageID».
        :param data: Telegram type: «bytes».
        """
        super().__init__()
        self.constructor_id = 0x2cbd95af

        self.query_id = query_id
        self.user_id = user_id
        self.msg_id = msg_id
        self.data = data

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.write_long(self.query_id)
        writer.write_int(self.user_id)
        self.msg_id.on_send(writer)
        writer.tgwrite_bytes(self.data)

    def on_response(self, reader):
        self.query_id = reader.read_long()
        self.user_id = reader.read_int()
        self.msg_id = reader.tgread_object()
        self.data = reader.tgread_bytes()

    def __repr__(self):
        return 'updateInlineBotCallbackQuery#2cbd95af query_id:long user_id:int msg_id:InputBotInlineMessageID data:bytes = Update'

    def __str__(self):
        return '(updateInlineBotCallbackQuery (ID: 0x2cbd95af) = (query_id={}, user_id={}, msg_id={}, data={}))'.format(str(self.query_id), str(self.user_id), str(self.msg_id), str(self.data))
