from telethon.tl.mtproto_request import MTProtoRequest


class UserStatusLastWeek(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    userStatusLastWeek#07bf09fc  = UserStatus"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x7bf09fc

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'userStatusLastWeek#07bf09fc  = UserStatus'

    def __str__(self):
        return '(userStatusLastWeek (ID: 0x7bf09fc) = ())'.format()
