from telethon.tl.mtproto_request import MTProtoRequest


class CodeTypeFlashCall(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    auth.codeTypeFlashCall#226ccefb  = auth.CodeType"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x226ccefb

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'auth.codeTypeFlashCall#226ccefb  = auth.CodeType'

    def __str__(self):
        return '(auth.codeTypeFlashCall (ID: 0x226ccefb) = ())'.format()
