
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "28d7740a5eb2457830d18a4f98f79bb105cf2e31",
 "version": "0.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
