
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1278f0eee08f69c68003f5b878f9512732fc6860",
 "version": "1.0.0.post.dev205"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
