from telethon.tl.mtproto_request import MTProtoRequest


class GetAuthorizationsRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    account.getAuthorizations#e320c158  = account.Authorizations"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0xe320c158

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'account.getAuthorizations#e320c158  = account.Authorizations'

    def __str__(self):
        return '(account.getAuthorizations (ID: 0xe320c158) = ())'.format()
