from telethon.tl.mtproto_request import MTProtoRequest


class GetAccountTTLRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    account.getAccountTTL#08fc711d  = AccountDaysTTL"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x8fc711d

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'account.getAccountTTL#08fc711d  = AccountDaysTTL'

    def __str__(self):
        return '(account.getAccountTTL (ID: 0x8fc711d) = ())'.format()
