from telethon.tl.mtproto_request import MTProtoRequest


class SetAccountTTLRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    account.setAccountTTL#2442485e ttl:AccountDaysTTL = Bool"""

    def __init__(self, ttl):
        """
        :param ttl: Telegram type: «AccountDaysTTL».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x2442485e

        self.ttl = ttl

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        self.ttl.on_send(writer)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'account.setAccountTTL#2442485e ttl:AccountDaysTTL = Bool'

    def __str__(self):
        return '(account.setAccountTTL (ID: 0x2442485e) = (ttl={}))'.format(str(self.ttl))
