# coding: utf-8
# Generated by setup.py for PyCBC on 2016-10-07 13:22:43 +0000.

version = '1.5.4'
date = '2016-10-07 13:21:59 +0000'
release = True
last_release = '1.5.4'

git_hash = '529d558830b01ad3fee4ff2e3e32db021e4d8c61'
git_branch = 'release'
git_tag = 'v1.5.4'
git_author = 'Alexander Harvey Nitz <alex.nitz@ligo.org>'
git_committer = 'Alexander Harvey Nitz <alex.nitz@ligo.org>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Alexander Harvey Nitz <alex.nitz@ligo.org>'
git_build_date = '2016-10-07 13:22:43 +0000'
git_verbose_msg = """Branch: release
Tag: v1.5.4
Id: 529d558830b01ad3fee4ff2e3e32db021e4d8c61
Builder: Alexander Harvey Nitz <alex.nitz@ligo.org>
Build date: 2016-10-07 13:22:43 +0000
Repository status is CLEAN: All modifications committed"""