from telethon.tl.mtproto_request import MTProtoRequest


class RecoverPasswordRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    auth.recoverPassword#4ea56e92 code:string = auth.Authorization"""

    def __init__(self, code):
        """
        :param code: Telegram type: «string».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x4ea56e92

        self.code = code

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_string(self.code)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'auth.recoverPassword#4ea56e92 code:string = auth.Authorization'

    def __str__(self):
        return '(auth.recoverPassword (ID: 0x4ea56e92) = (code={}))'.format(str(self.code))
