
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "24bf97e1acd86a42d46a008bee12c88c0e2f115b",
 "version": "1.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
