
- instance:
    input:
        name: genetalk_db_machine 
        #image_id: ami-4b1c3728 
        #        image_id: ami-34fcd757 
        keyname: ap-southeast-2_default_test_access_key 
        subnet_id:
            value: subnet-3d2e377b 
        number: 1
        instance_type: t2.micro 
        security_group_ids:
            value: [sg-70bd2e14]
        tags:
            - tag:
                key: Name
                value: genetalk_test_instance 

 
#    vpc:
#       from_config: ./libaws/demo/vpc_config.yaml
#    
#    keypair:
#        key: genetalk_access_key   
#        delete_exists: True
#
# volumes:
#       - volume:
#           size: 20
#           name: /dev/sda1

