
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-10-12T09:08:57+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "aa3b2d7406d3b482274ea17750079a6ef4268ece",
 "version": "0.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
