
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.23.24'
version_full = '990fd431f3d03d5b378a75138a4ba16998e0a12a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

