
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-10-12T14:08:52+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "85e2e4befba3fce995a86a5a46c05630d5ebd883",
 "version": "1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
