# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 02:37
from __future__ import unicode_literals
from django.conf import settings

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouroboros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ouroboros.CourseInstance')),
                ('node_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ouroboros.NodeSpec')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
