# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouroboros', '0002_courseinstancelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespec',
            name='code',
            field=models.SlugField(blank=True, help_text='Internal (unique) code', max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='coursespec',
            name='description',
            field=models.TextField(blank=True, max_length=1023, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='nodespec',
            name='code',
            field=models.SlugField(help_text='Internal (unique) code', max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='nodespec',
            name='description',
            field=models.TextField(blank=True, max_length=1023, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transitionspec',
            name='action_name',
            field=models.SlugField(blank=True, help_text='Action name for this transition. Unique with respect to the origin node. Expected only for split and input nodes', max_length=30, null=True, verbose_name='Action Name'),
        ),
        migrations.AlterField(
            model_name='transitionspec',
            name='description',
            field=models.TextField(blank=True, max_length=1023, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workflowspec',
            name='code',
            field=models.SlugField(help_text='Internal (unique) code', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='workflowspec',
            name='description',
            field=models.TextField(blank=True, max_length=1023, verbose_name='Description'),
        ),
    ]
