# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouroboros', '0003_auto_20160809_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespec',
            name='translated',
            field=models.BooleanField(default=True, help_text='Tells whether description', verbose_name='Translated'),
        ),
        migrations.AddField(
            model_name='nodespec',
            name='translated',
            field=models.BooleanField(default=True, help_text='Tells whether description', verbose_name='Translated'),
        ),
        migrations.AddField(
            model_name='transitionspec',
            name='translated',
            field=models.BooleanField(default=True, help_text='Tells whether description', verbose_name='Translated'),
        ),
        migrations.AddField(
            model_name='workflowspec',
            name='translated',
            field=models.BooleanField(default=True, help_text='Tells whether description', verbose_name='Translated'),
        ),
    ]
