
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "462b218bbbfc4743f050d8797e2d5aa5aebd7767",
 "version": "0.1.8.post.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
