# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magenta/protobuf/generator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='magenta/protobuf/generator.proto',
  package='tensorflow.magenta',
  syntax='proto3',
  serialized_pb=_b('\n magenta/protobuf/generator.proto\x12\x12tensorflow.magenta\"3\n\x10GeneratorDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\xac\x01\n\x10GeneratorOptions\x12O\n\x11generate_sections\x18\x01 \x03(\x0b\x32\x34.tensorflow.magenta.GeneratorOptions.GenerateSection\x1aG\n\x0fGenerateSection\x12\x1a\n\x12start_time_seconds\x18\x01 \x01(\x01\x12\x18\n\x10\x65nd_time_seconds\x18\x02 \x01(\x01\"\xf4\x01\n\x0fGeneratorBundle\x12?\n\x11generator_details\x18\x01 \x01(\x0b\x32$.tensorflow.magenta.GeneratorDetails\x12I\n\x0e\x62undle_details\x18\x04 \x01(\x0b\x32\x31.tensorflow.magenta.GeneratorBundle.BundleDetails\x12\x17\n\x0f\x63heckpoint_file\x18\x02 \x03(\x0c\x12\x16\n\x0emetagraph_file\x18\x03 \x01(\x0c\x1a$\n\rBundleDetails\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GENERATORDETAILS = _descriptor.Descriptor(
  name='GeneratorDetails',
  full_name='tensorflow.magenta.GeneratorDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tensorflow.magenta.GeneratorDetails.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='tensorflow.magenta.GeneratorDetails.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=107,
)


_GENERATOROPTIONS_GENERATESECTION = _descriptor.Descriptor(
  name='GenerateSection',
  full_name='tensorflow.magenta.GeneratorOptions.GenerateSection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time_seconds', full_name='tensorflow.magenta.GeneratorOptions.GenerateSection.start_time_seconds', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time_seconds', full_name='tensorflow.magenta.GeneratorOptions.GenerateSection.end_time_seconds', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=282,
)

_GENERATOROPTIONS = _descriptor.Descriptor(
  name='GeneratorOptions',
  full_name='tensorflow.magenta.GeneratorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='generate_sections', full_name='tensorflow.magenta.GeneratorOptions.generate_sections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GENERATOROPTIONS_GENERATESECTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=282,
)


_GENERATORBUNDLE_BUNDLEDETAILS = _descriptor.Descriptor(
  name='BundleDetails',
  full_name='tensorflow.magenta.GeneratorBundle.BundleDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='tensorflow.magenta.GeneratorBundle.BundleDetails.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=529,
)

_GENERATORBUNDLE = _descriptor.Descriptor(
  name='GeneratorBundle',
  full_name='tensorflow.magenta.GeneratorBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='generator_details', full_name='tensorflow.magenta.GeneratorBundle.generator_details', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bundle_details', full_name='tensorflow.magenta.GeneratorBundle.bundle_details', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checkpoint_file', full_name='tensorflow.magenta.GeneratorBundle.checkpoint_file', index=2,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metagraph_file', full_name='tensorflow.magenta.GeneratorBundle.metagraph_file', index=3,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GENERATORBUNDLE_BUNDLEDETAILS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=529,
)

_GENERATOROPTIONS_GENERATESECTION.containing_type = _GENERATOROPTIONS
_GENERATOROPTIONS.fields_by_name['generate_sections'].message_type = _GENERATOROPTIONS_GENERATESECTION
_GENERATORBUNDLE_BUNDLEDETAILS.containing_type = _GENERATORBUNDLE
_GENERATORBUNDLE.fields_by_name['generator_details'].message_type = _GENERATORDETAILS
_GENERATORBUNDLE.fields_by_name['bundle_details'].message_type = _GENERATORBUNDLE_BUNDLEDETAILS
DESCRIPTOR.message_types_by_name['GeneratorDetails'] = _GENERATORDETAILS
DESCRIPTOR.message_types_by_name['GeneratorOptions'] = _GENERATOROPTIONS
DESCRIPTOR.message_types_by_name['GeneratorBundle'] = _GENERATORBUNDLE

GeneratorDetails = _reflection.GeneratedProtocolMessageType('GeneratorDetails', (_message.Message,), dict(
  DESCRIPTOR = _GENERATORDETAILS,
  __module__ = 'magenta.protobuf.generator_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.magenta.GeneratorDetails)
  ))
_sym_db.RegisterMessage(GeneratorDetails)

GeneratorOptions = _reflection.GeneratedProtocolMessageType('GeneratorOptions', (_message.Message,), dict(

  GenerateSection = _reflection.GeneratedProtocolMessageType('GenerateSection', (_message.Message,), dict(
    DESCRIPTOR = _GENERATOROPTIONS_GENERATESECTION,
    __module__ = 'magenta.protobuf.generator_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.magenta.GeneratorOptions.GenerateSection)
    ))
  ,
  DESCRIPTOR = _GENERATOROPTIONS,
  __module__ = 'magenta.protobuf.generator_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.magenta.GeneratorOptions)
  ))
_sym_db.RegisterMessage(GeneratorOptions)
_sym_db.RegisterMessage(GeneratorOptions.GenerateSection)

GeneratorBundle = _reflection.GeneratedProtocolMessageType('GeneratorBundle', (_message.Message,), dict(

  BundleDetails = _reflection.GeneratedProtocolMessageType('BundleDetails', (_message.Message,), dict(
    DESCRIPTOR = _GENERATORBUNDLE_BUNDLEDETAILS,
    __module__ = 'magenta.protobuf.generator_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.magenta.GeneratorBundle.BundleDetails)
    ))
  ,
  DESCRIPTOR = _GENERATORBUNDLE,
  __module__ = 'magenta.protobuf.generator_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.magenta.GeneratorBundle)
  ))
_sym_db.RegisterMessage(GeneratorBundle)
_sym_db.RegisterMessage(GeneratorBundle.BundleDetails)


# @@protoc_insertion_point(module_scope)
