
# This file is automatically generated from sisl setup.py
major   = 0
minor   = 7
micro   = 6
version = '.'.join(map(str,[0, 7, 6]))
release = True
# Git information
git_rev = '74d7baa8f55bd410a3968284a93a6c849a53ab6c'
git_rev_short = git_rev[:7]

if not release:
    version = version + '-' + git_rev_short
