
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b4769fd799cf8c9ae4547dc05bba877a438b91d3",
 "version": "0.post.dev353"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
