
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.0'
version_full = '25aadaf479aa2a5149c4163f53b226643f622eb4'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

