
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(BuildFileAddress(FilesystemBuildFile(/Users/jdorlus/dev/GitHub/twitter_commons/src/python/twitter/common/jira/BUILD), jira))

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': 'twitter.common thin library for interacting with JIRA.',
    'install_requires': ['twitter.common.log==0.3.9'],
    'license': 'Apache License, Version 2.0',
    'name': 'twitter.common.jira',
    'namespace_packages': ['twitter', 'twitter.common'],
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': ['twitter', 'twitter.common', 'twitter.common.jira'],
    'url': 'https://github.com/twitter/commons',
    'version': '0.3.9',
    'zip_safe': True}
)
