IV = """arise	arose	arisen
babysit	babysat	babysat
be	was	been
beat	beat	beaten
become	became	become
bend	bent	bent
begin	began	begun
bet	bet	bet
bind	bound	bound
bite	bit	bitten
bleed	bled	bled
blow	blew	blown
break	broke	broken
breed	bred	bred
bring	brought	brought
broadcast	broadcast	broadcast
build	built	built
buy	bought	bought
catch	caught	caught
choose	chose	chosen
come	came	come
cost	cost	cost
cut	cut	cut
deal	dealt	dealt
dig	dug	dug
do	did	done
draw	drew	drawn
drink	drank	drunk
drive	drove	driven
eat	ate	eaten
fall	fell	fallen
feed	fed	fed
feel	felt	felt
fight	fought	fought
find	found	found
fly	flew	flown
forbid	forbade	forbidden
forget	forgot	forgotten
forgive	forgave	forgiven
freeze	froze	frozen
get	got	gotten
give	gave	given
go	went	gone
grow	grew	grown
hang	hung	hung
have	had	had
hear	heard	heard
hide	hid	hidden
hit	hit	hit
hold	held	held
hurt	hurt	hurt
keep	kept	kept
know	knew	known
lay	laid	laid
lead	led	led
leave	left	left
lend	lent	lent
let	let	let
lie	lay	lain
light	lit	lit
lose	lost	lost
make	made	made
mean	meant	meant
meet	met	met
pay	paid	paid
put	put	put
quit	quit	quit
read	read	read
ride	rode	ridden
ring	rang	rung
rise	rose	risen
run	ran	run
say	said	said
see	saw	seen
sell	sold	sold
send	sent	sent
set	set	set
shake	shook	shaken
shine	shone	shone
shoot	shot	shot
show	showed	shown
shut	shut	shut
sing	sang	sung
sink	sank	sunk
sit	sat	sat
sleep	slept	slept
slide	slid	slid
speak	spoke	spoken
spend	spent	spent
spin	spun	spun
spread	spread	spread
stand	stood	stood
steal	stole	stolen
stick	stuck	stuck
sting	stung	stung
strike	struck	struck
swear	swore	sworn
sweep	swept	swept
swim	swam	swum
swing	swung	swung
take	took	taken
teach	taught	taught
tear	tore	torn
tell	told	told
think	thought	thought
throw	threw	thrown
understand	understood	understood
wake	woke	woken
wear	wore	worn
win	won	won
withdraw	withdrew	withdrawn
write	wrote	written"""