from telethon.tl.mtproto_request import MTProtoRequest


class GetPeerSettingsRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messages.getPeerSettings#3672e09c peer:InputPeer = PeerSettings"""

    def __init__(self, peer):
        """
        :param peer: Telegram type: «InputPeer».
        """
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0x3672e09c

        self.peer = peer

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        self.peer.on_send(writer)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'messages.getPeerSettings#3672e09c peer:InputPeer = PeerSettings'

    def __str__(self):
        return '(messages.getPeerSettings (ID: 0x3672e09c) = (peer={}))'.format(str(self.peer))
