from telethon.tl.mtproto_request import MTProtoRequest


class ReadFeaturedStickersRequest(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    messages.readFeaturedStickers#00e21cbb  = Bool"""

    def __init__(self):
        super().__init__()
        self.result = None
        self.confirmed = True  # Confirmed by default
        self.constructor_id = 0xe21cbb

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        self.result = reader.tgread_object()

    def __repr__(self):
        return 'messages.readFeaturedStickers#00e21cbb  = Bool'

    def __str__(self):
        return '(messages.readFeaturedStickers (ID: 0xe21cbb) = ())'.format()
