
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.23.23'
version_full = 'b9e5ad31c0fc62dbcb71d4b99a8b7ae4c3b43ce9'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

