#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

AppIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABC9J"
    "REFUWIW1V11IXEcU/mZmd9kf3W38SZZgE/fnwaSFBAKirYQSS9Ai1Bvqe+mDSJHggy0SggRZ"
    "EET64EMopRTpQwgJNBsbzENQ2gRiECmJFJHEVUz8TYvRzd51d++9M32J292797p7W/0ez5lz"
    "vm/O/JwZIoQgsIj3xpa+ULhoyrXZCKZ3Pg/esJrLZjUAAJIKv64AVbk2BpG8DdzsALiVXNQq"
    "eeuj9So9OQBoIO7ByaUaq/lMK1AWXejmgvjP+B2Rqcb3U3v22e102CxmVeZhAC+zYu+/cPye"
    "ZleIEAlZCg0bxRhWoDwauyprZGSX48rMWuZxzb1YllTmWp2ZgBQnWZ9/bLl2Ikl/29VEf5Jj"
    "yH0nNmQUQ/SbsDwau5rQMKBTGXdSRFSIixmOCwAxWTrB7YQ8dDKMy6ro4yAVuV4XJUNJKdhn"
    "KqAsutAta2TEbIYHATdDn9weylYjbyZcEP9hkhtx5Ak443dEbMAfh0XOCOZO0kx/rq1gD9Tc"
    "i4XX05jhgPcgyYkQyWo3bdj8LPhnrr1gM620hRacFJGDJAcAt40O68kNBQCAAnFxv2ROSsYr"
    "Hfj0K7/P+80HPm+13dbkIri1X4wijHNml6D10XrV7HY6LHOtbkcVP5odtTKG/rftIcMK+aJL"
    "nXGNf28mwstol5OR2Q/drsWJ5mOvAYD47i52GN3tRnBSMr4rBdv2G+O+s/jTLhdfFstlJ2LL"
    "SVkPVbhoKoUcALw28V2xMcddNsMrVw9FkIqExs9bakZtFb7pYmMGW07M2wkSpea0JOBImVq0"
    "1b5rxyW3ZEsCfl5Ony025vSDlbAiSr9DqI1gmpVYsoSqXi42ZlnOdJeSixGR8jDyhAghyG2A"
    "Dk4u1azKPJzipC6u8hGzY+hltGunPfCDka/y18VLbzL8ljCJLWek18XE00oPXejxBdY6z0Et"
    "uIoBwPFLbFIR+MRMvYuS0eMu2/Bgy4n5DoCffrASXpYz3buq+FoQ40eOg4qZtBSu19sNBXjv"
    "xnrfqjB8QOTi3W7npay5m+KaLIUG9PYCAf6x5dq/FGVG/5j4v6BA3O+h9astgec6+79ovf/C"
    "saWoNw6aHAA44N2U+c3GqVdOUwEPU7RPARoOmnwPGnD22UZG/9zLQ/KwyPdAkH/k8wTIUmjY"
    "RUnB5iNCJD2MRBwEj4sROKiYcVNco0Bc73NTXB+V8jtpwXlNSsE+F0W2oTCCuWo3bUi0B/vT"
    "l0JNXka7zMjLGelNS+F6WQoN+D20ngFPdeSX9T8nwzOblELfeqKxv7kg/pNHvf3zH1dly+Zk"
    "ZDaumcyeiSzhakvgeePUq4+ebWQGCJAYlUIRo2+b4T2wH5onNo9Obic2jHynjtDauQuBl0Y+"
    "M1j+G040H3ttJ2JLb2dEpHp8gTWr+f7T79hOWY+q8fO5NhelTzrPQbWa6x8c+J95ZcStkQAA"
    "AABJRU5ErkJggg==")

