from telethon.tl.mtproto_request import MTProtoRequest


class CodeTypeSms(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    auth.codeTypeSms#72a3158c  = auth.CodeType"""

    def __init__(self):
        super().__init__()
        self.constructor_id = 0x72a3158c

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)

    def on_response(self, reader):
        pass

    def __repr__(self):
        return 'auth.codeTypeSms#72a3158c  = auth.CodeType'

    def __str__(self):
        return '(auth.codeTypeSms (ID: 0x72a3158c) = ())'.format()
