from telethon.tl.mtproto_request import MTProtoRequest


class PasswordRecovery(MTProtoRequest):
    """Class generated by TLObjects' generator. All changes will be ERASED. Original .tl definition below.
    auth.passwordRecovery#137948a5 email_pattern:string = auth.PasswordRecovery"""

    def __init__(self, email_pattern):
        """
        :param email_pattern: Telegram type: «string».
        """
        super().__init__()
        self.constructor_id = 0x137948a5

        self.email_pattern = email_pattern

    def on_send(self, writer):
        writer.write_int(self.constructor_id, signed=False)
        writer.tgwrite_string(self.email_pattern)

    def on_response(self, reader):
        self.email_pattern = reader.tgread_string()

    def __repr__(self):
        return 'auth.passwordRecovery#137948a5 email_pattern:string = auth.PasswordRecovery'

    def __str__(self):
        return '(auth.passwordRecovery (ID: 0x137948a5) = (email_pattern={}))'.format(str(self.email_pattern))
